module.exports = [ {name: 'Abadia dos Dourados'},
{name: 'Abaeté'},
{name: 'Abre Campo'},
{name: 'Acaiaca'},
{name: 'Açucena'},
{name: 'Água Boa'},
{name: 'Água Comprida'},
{name: 'Aguanil'},
{name: 'Águas Formosas'},
{name: 'Águas Vermelhas'},
{name: 'Aimorés'},
{name: 'Aiuruoca'},
{name: 'Alagoa'},
{name: 'Albertina'},
{name: 'Além Paraíba'},
{name: 'Alfenas'},
{name: 'Alfredo Vasconcelos'},
{name: 'Almenara'},
{name: 'Alpercata'},
{name: 'Alpinópolis'},
{name: 'Alterosa'},
{name: 'Alto Caparaó'},
{name: 'Alto Jequitibá'},
{name: 'Alto Rio Doce'},
{name: 'Alvarenga'},
{name: 'Alvinópolis'},
{name: 'Alvorada de Minas'},
{name: 'Amparo do Serra'},
{name: 'Andradas'},
{name: 'Andrelândia'},
{name: 'Angelândia'},
{name: 'Antônio Carlos'},
{name: 'Antônio Dias'},
{name: 'Antônio Prado de Minas'},
{name: 'Araçaí'},
{name: 'Aracitaba'},
{name: 'Araçuaí'},
{name: 'Araguari'},
{name: 'Arantina'},
{name: 'Araponga'},
{name: 'Araporã'},
{name: 'Arapuá'},
{name: 'Araújos'},
{name: 'Araxá'},
{name: 'Arceburgo'},
{name: 'Arcos'},
{name: 'Areado'},
{name: 'Argirita'},
{name: 'Aricanduva'},
{name: 'Arinos'},
{name: 'Astolfo Dutra'},
{name: 'Ataléia'},
{name: 'Augusto de Lima'},
{name: 'Baependi'},
{name: 'Baldim'},
{name: 'Bambuí'},
{name: 'Bandeira'},
{name: 'Bandeira do Sul'},
{name: 'Barão de Cocais'},
{name: 'Barão de Monte Alto'},
{name: 'Barbacena'},
{name: 'Barra Longa'},
{name: 'Barroso'},
{name: 'Bela Vista de Minas'},
{name: 'Belmiro Braga'},
{name: 'Belo Horizonte'},
{name: 'Belo Oriente'},
{name: 'Belo Vale'},
{name: 'Berilo'},
{name: 'Berizal'},
{name: 'Bertópolis'},
{name: 'Betim'},
{name: 'Bias Fortes'},
{name: 'Bicas'},
{name: 'Biquinhas'},
{name: 'Boa Esperança'},
{name: 'Bocaina de Minas'},
{name: 'Bocaiúva'},
{name: 'Bom Despacho'},
{name: 'Bom Jardim de Minas'},
{name: 'Bom Jesus da Penha'},
{name: 'Bom Jesus do Amparo'},
{name: 'Bom Jesus do Galho'},
{name: 'Bom Repouso'},
{name: 'Bom Sucesso'},
{name: 'Bonfim'},
{name: 'Bonfinópolis de Minas'},
{name: 'Bonito de Minas'},
{name: 'Borda da Mata'},
{name: 'Botelhos'},
{name: 'Botumirim'},
{name: 'Brás Pires'},
{name: 'Brasilândia de Minas'},
{name: 'Brasília de Minas'},
{name: 'Brasópolis'},
{name: 'Braúnas'},
{name: 'Brumadinho'},
{name: 'Bueno Brandão'},
{name: 'Buenópolis'},
{name: 'Bugre'},
{name: 'Buritis'},
{name: 'Buritizeiro'},
{name: 'Cabeceira Grande'},
{name: 'Cabo Verde'},
{name: 'Cachoeira da Prata'},
{name: 'Cachoeira de Minas'},
{name: 'Cachoeira de Pajeú'},
{name: 'Cachoeira Dourada'},
{name: 'Caetanópolis'},
{name: 'Caeté'},
{name: 'Caiana'},
{name: 'Cajuri'},
{name: 'Caldas'},
{name: 'Camacho'},
{name: 'Camanducaia'},
{name: 'Cambuí'},
{name: 'Cambuquira'},
{name: 'Campanário'},
{name: 'Campanha'},
{name: 'Campestre'},
{name: 'Campina Verde'},
{name: 'Campo Azul'},
{name: 'Campo Belo'},
{name: 'Campo do Meio'},
{name: 'Campo Florido'},
{name: 'Campos Altos'},
{name: 'Campos Gerais'},
{name: 'Cana Verde'},
{name: 'Canaã'},
{name: 'Canápolis'},
{name: 'Candeias'},
{name: 'Cantagalo'},
{name: 'Caparaó'},
{name: 'Capela Nova'},
{name: 'Capelinha'},
{name: 'Capetinga'},
{name: 'Capim Branco'},
{name: 'Capinópolis'},
{name: 'Capitão Andrade'},
{name: 'Capitão Enéas'},
{name: 'Capitólio'},
{name: 'Caputira'},
{name: 'Caraí'},
{name: 'Caranaíba'},
{name: 'Carandaí'},
{name: 'Carangola'},
{name: 'Caratinga'},
{name: 'Carbonita'},
{name: 'Careaçu'},
{name: 'Carlos Chagas'},
{name: 'Carmésia'},
{name: 'Carmo da Cachoeira'},
{name: 'Carmo da Mata'},
{name: 'Carmo de Minas'},
{name: 'Carmo do Cajuru'},
{name: 'Carmo do Paranaíba'},
{name: 'Carmo do Rio Claro'},
{name: 'Carmópolis de Minas'},
{name: 'Carneirinho'},
{name: 'Carrancas'},
{name: 'Carvalhópolis'},
{name: 'Carvalhos'},
{name: 'Casa Grande'},
{name: 'Cascalho Rico'},
{name: 'Cássia'},
{name: 'Cataguases'},
{name: 'Catas Altas'},
{name: 'Catas Altas da Noruega'},
{name: 'Catuji'},
{name: 'Catuti'},
{name: 'Caxambu'},
{name: 'Cedro do Abaeté'},
{name: 'Central de Minas'},
{name: 'Centralina'},
{name: 'Chácara'},
{name: 'Chalé'},
{name: 'Chapada do Norte'},
{name: 'Chapada Gaúcha'},
{name: 'Chiador'},
{name: 'Cipotânea'},
{name: 'Claraval'},
{name: 'Claro dos Poções'},
{name: 'Cláudio'},
{name: 'Coimbra'},
{name: 'Coluna'},
{name: 'Comendador Gomes'},
{name: 'Comercinho'},
{name: 'Conceição da Aparecida'},
{name: 'Conceição da Barra de Minas'},
{name: 'Conceição das Alagoas'},
{name: 'Conceição das Pedras'},
{name: 'Conceição de Ipanema'},
{name: 'Conceição do Mato Dentro'},
{name: 'Conceição do Pará'},
{name: 'Conceição do Rio Verde'},
{name: 'Conceição dos Ouros'},
{name: 'Cônego Marinho'},
{name: 'Confins'},
{name: 'Congonhal'},
{name: 'Congonhas'},
{name: 'Congonhas do Norte'},
{name: 'Conquista'},
{name: 'Conselheiro Lafaiete'},
{name: 'Conselheiro Pena'},
{name: 'Consolação'},
{name: 'Contagem'},
{name: 'Coqueiral'},
{name: 'Coração de Jesus'},
{name: 'Cordisburgo'},
{name: 'Cordislândia'},
{name: 'Corinto'},
{name: 'Coroaci'},
{name: 'Coromandel'},
{name: 'Coronel Fabriciano'},
{name: 'Coronel Murta'},
{name: 'Coronel Pacheco'},
{name: 'Coronel Xavier Chaves'},
{name: 'Córrego Danta'},
{name: 'Córrego do Bom Jesus'},
{name: 'Córrego Fundo'},
{name: 'Córrego Novo'},
{name: 'Couto de Magalhães de Minas'},
{name: 'Crisólita'},
{name: 'Cristais'},
{name: 'Cristália'},
{name: 'Cristiano Otoni'},
{name: 'Cristina'},
{name: 'Crucilândia'},
{name: 'Cruzeiro da Fortaleza'},
{name: 'Cruzília'},
{name: 'Cuparaque'},
{name: 'Curral de Dentro'},
{name: 'Curvelo'},
{name: 'Datas'},
{name: 'Delfim Moreira'},
{name: 'Delfinópolis'},
{name: 'Delta'},
{name: 'Descoberto'},
{name: 'Desterro de Entre Rios'},
{name: 'Desterro do Melo'},
{name: 'Diamantina'},
{name: 'Diogo de Vasconcelos'},
{name: 'Dionísio'},
{name: 'Divinésia'},
{name: 'Divino'},
{name: 'Divino das Laranjeiras'},
{name: 'Divinolândia de Minas'},
{name: 'Divinópolis'},
{name: 'Divisa Alegre'},
{name: 'Divisa Nova'},
{name: 'Divisópolis'},
{name: 'Dom Bosco'},
{name: 'Dom Cavati'},
{name: 'Dom Joaquim'},
{name: 'Dom Silvério'},
{name: 'Dom Viçoso'},
{name: 'Dona Eusébia'},
{name: 'Dores de Campos'},
{name: 'Dores de Guanhães'},
{name: 'Dores do Indaiá'},
{name: 'Dores do Turvo'},
{name: 'Doresópolis'},
{name: 'Douradoquara'},
{name: 'Durandé'},
{name: 'Elói Mendes'},
{name: 'Engenheiro Caldas'},
{name: 'Engenheiro Navarro'},
{name: 'Entre Folhas'},
{name: 'Entre Rios de Minas'},
{name: 'Ervália'},
{name: 'Esmeraldas'},
{name: 'Espera Feliz'},
{name: 'Espinosa'},
{name: 'Espírito Santo do Dourado'},
{name: 'Estiva'},
{name: 'Estrela Dalva'},
{name: 'Estrela do Indaiá'},
{name: 'Estrela do Sul'},
{name: 'Eugenópolis'},
{name: 'Ewbank da Câmara'},
{name: 'Extrema'},
{name: 'Fama'},
{name: 'Faria Lemos'},
{name: 'Felício dos Santos'},
{name: 'Felisburgo'},
{name: 'Felixlândia'},
{name: 'Fernandes Tourinho'},
{name: 'Ferros'},
{name: 'Fervedouro'},
{name: 'Florestal'},
{name: 'Formiga'},
{name: 'Formoso'},
{name: 'Fortaleza de Minas'},
{name: 'Fortuna de Minas'},
{name: 'Francisco Badaró'},
{name: 'Francisco Dumont'},
{name: 'Francisco Sá'},
{name: 'Franciscópolis'},
{name: 'Frei Gaspar'},
{name: 'Frei Inocêncio'},
{name: 'Frei Lagonegro'},
{name: 'Fronteira'},
{name: 'Fronteira dos Vales'},
{name: 'Fruta de Leite'},
{name: 'Frutal'},
{name: 'Funilândia'},
{name: 'Galiléia'},
{name: 'Gameleiras'},
{name: 'Glaucilândia'},
{name: 'Goiabeira'},
{name: 'Goianá'},
{name: 'Gonçalves'},
{name: 'Gonzaga'},
{name: 'Gouveia'},
{name: 'Governador Valadares'},
{name: 'Grão Mogol'},
{name: 'Grupiara'},
{name: 'Guanhães'},
{name: 'Guapé'},
{name: 'Guaraciaba'},
{name: 'Guaraciama'},
{name: 'Guaranésia'},
{name: 'Guarani'},
{name: 'Guarará'},
{name: 'Guarda-Mor'},
{name: 'Guaxupé'},
{name: 'Guidoval'},
{name: 'Guimarânia'},
{name: 'Guiricema'},
{name: 'Gurinhatã'},
{name: 'Heliodora'},
{name: 'Iapu'},
{name: 'Ibertioga'},
{name: 'Ibiá'},
{name: 'Ibiaí'},
{name: 'Ibiracatu'},
{name: 'Ibiraci'},
{name: 'Ibirité'},
{name: 'Ibitiúra de Minas'},
{name: 'Ibituruna'},
{name: 'Icaraí de Minas'},
{name: 'Igarapé'},
{name: 'Igaratinga'},
{name: 'Iguatama'},
{name: 'Ijaci'},
{name: 'Ilicínea'},
{name: 'Imbé de Minas'},
{name: 'Inconfidentes'},
{name: 'Indaiabira'},
{name: 'Indianópolis'},
{name: 'Ingaí'},
{name: 'Inhapim'},
{name: 'Inhaúma'},
{name: 'Inimutaba'},
{name: 'Ipaba'},
{name: 'Ipanema'},
{name: 'Ipatinga'},
{name: 'Ipiaçu'},
{name: 'Ipuiúna'},
{name: 'Iraí de Minas'},
{name: 'Itabira'},
{name: 'Itabirinha de Mantena'},
{name: 'Itabirito'},
{name: 'Itacambira'},
{name: 'Itacarambi'},
{name: 'Itaguara'},
{name: 'Itaipé'},
{name: 'Itajubá'},
{name: 'Itamarandiba'},
{name: 'Itamarati de Minas'},
{name: 'Itambacuri'},
{name: 'Itambé do Mato Dentro'},
{name: 'Itamogi'},
{name: 'Itamonte'},
{name: 'Itanhandu'},
{name: 'Itanhomi'},
{name: 'Itaobim'},
{name: 'Itapagipe'},
{name: 'Itapecerica'},
{name: 'Itapeva'},
{name: 'Itatiaiuçu'},
{name: 'Itaú de Minas'},
{name: 'Itaúna'},
{name: 'Itaverava'},
{name: 'Itinga'},
{name: 'Itueta'},
{name: 'Ituiutaba'},
{name: 'Itumirim'},
{name: 'Iturama'},
{name: 'Itutinga'},
{name: 'Jaboticatubas'},
{name: 'Jacinto'},
{name: 'Jacuí'},
{name: 'Jacutinga'},
{name: 'Jaguaraçu'},
{name: 'Jaíba'},
{name: 'Jampruca'},
{name: 'Janaúba'},
{name: 'Januária'},
{name: 'Japaraíba'},
{name: 'Japonvar'},
{name: 'Jeceaba'},
{name: 'Jenipapo de Minas'},
{name: 'Jequeri'},
{name: 'Jequitaí'},
{name: 'Jequitibá'},
{name: 'Jequitinhonha'},
{name: 'Jesuânia'},
{name: 'Joaíma'},
{name: 'Joanésia'},
{name: 'João Monlevade'},
{name: 'João Pinheiro'},
{name: 'Joaquim Felício'},
{name: 'Jordânia'},
{name: 'José Gonçalves de Minas'},
{name: 'José Raydan'},
{name: 'Josenópolis'},
{name: 'Juatuba'},
{name: 'Juiz de Fora'},
{name: 'Juramento'},
{name: 'Juruaia'},
{name: 'Juvenília'},
{name: 'Ladainha'},
{name: 'Lagamar'},
{name: 'Lagoa da Prata'},
{name: 'Lagoa dos Patos'},
{name: 'Lagoa Dourada'},
{name: 'Lagoa Formosa'},
{name: 'Lagoa Grande'},
{name: 'Lagoa Santa'},
{name: 'Lajinha'},
{name: 'Lambari'},
{name: 'Lamim'},
{name: 'Laranjal'},
{name: 'Lassance'},
{name: 'Lavras'},
{name: 'Leandro Ferreira'},
{name: 'Leme do Prado'},
{name: 'Leopoldina'},
{name: 'Liberdade'},
{name: 'Lima Duarte'},
{name: 'Limeira do Oeste'},
{name: 'Lontra'},
{name: 'Luisburgo'},
{name: 'Luislândia'},
{name: 'Luminárias'},
{name: 'Luz'},
{name: 'Machacalis'},
{name: 'Machado'},
{name: 'Madre de Deus de Minas'},
{name: 'Malacacheta'},
{name: 'Mamonas'},
{name: 'Manga'},
{name: 'Manhuaçu'},
{name: 'Manhumirim'},
{name: 'Mantena'},
{name: 'Mar de Espanha'},
{name: 'Maravilhas'},
{name: 'Maria da Fé'},
{name: 'Mariana'},
{name: 'Marilac'},
{name: 'Mário Campos'},
{name: 'Maripá de Minas'},
{name: 'Marliéria'},
{name: 'Marmelópolis'},
{name: 'Martinho Campos'},
{name: 'Martins Soares'},
{name: 'Mata Verde'},
{name: 'Materlândia'},
{name: 'Mateus Leme'},
{name: 'Mathias Lobato'},
{name: 'Matias Barbosa'},
{name: 'Matias Cardoso'},
{name: 'Matipó'},
{name: 'Mato Verde'},
{name: 'Matozinhos'},
{name: 'Matutina'},
{name: 'Medeiros'},
{name: 'Medina'},
{name: 'Mendes Pimentel'},
{name: 'Mercês'},
{name: 'Mesquita'},
{name: 'Minas Novas'},
{name: 'Minduri'},
{name: 'Mirabela'},
{name: 'Miradouro'},
{name: 'Miraí'},
{name: 'Miravânia'},
{name: 'Moeda'},
{name: 'Moema'},
{name: 'Monjolos'},
{name: 'Monsenhor Paulo'},
{name: 'Montalvânia'},
{name: 'Monte Alegre de Minas'},
{name: 'Monte Azul'},
{name: 'Monte Belo'},
{name: 'Monte Carmelo'},
{name: 'Monte Formoso'},
{name: 'Monte Santo de Minas'},
{name: 'Monte Sião'},
{name: 'Montes Claros'},
{name: 'Montezuma'},
{name: 'Morada Nova de Minas'},
{name: 'Morro da Garça'},
{name: 'Morro do Pilar'},
{name: 'Munhoz'},
{name: 'Muriaé'},
{name: 'Mutum'},
{name: 'Muzambinho'},
{name: 'Nacip Raydan'},
{name: 'Nanuque'},
{name: 'Naque'},
{name: 'Natalândia'},
{name: 'Natércia'},
{name: 'Nazareno'},
{name: 'Nepomuceno'},
{name: 'Ninheira'},
{name: 'Nova Belém'},
{name: 'Nova Era'},
{name: 'Nova Lima'},
{name: 'Nova Módica'},
{name: 'Nova Ponte'},
{name: 'Nova Porteirinha'},
{name: 'Nova Resende'},
{name: 'Nova Serrana'},
{name: 'Nova União'},
{name: 'Novo Cruzeiro'},
{name: 'Novo Oriente de Minas'},
{name: 'Novorizonte'},
{name: 'Olaria'},
{name: 'Olhos-d`Água'},
{name: 'Olímpio Noronha'},
{name: 'Oliveira'},
{name: 'Oliveira Fortes'},
{name: 'Onça de Pitangui'},
{name: 'Oratórios'},
{name: 'Orizânia'},
{name: 'Ouro Branco'},
{name: 'Ouro Fino'},
{name: 'Ouro Preto'},
{name: 'Ouro Verde de Minas'},
{name: 'Padre Carvalho'},
{name: 'Padre Paraíso'},
{name: 'Pai Pedro'},
{name: 'Paineiras'},
{name: 'Pains'},
{name: 'Paiva'},
{name: 'Palma'},
{name: 'Palmópolis'},
{name: 'Papagaios'},
{name: 'Pará de Minas'},
{name: 'Paracatu'},
{name: 'Paraguaçu'},
{name: 'Paraisópolis'},
{name: 'Paraopeba'},
{name: 'Passa Quatro'},
{name: 'Passa Tempo'},
{name: 'Passabém'},
{name: 'Passa-Vinte'},
{name: 'Passos'},
{name: 'Patis'},
{name: 'Patos de Minas'},
{name: 'Patrocínio'},
{name: 'Patrocínio do Muriaé'},
{name: 'Paula Cândido'},
{name: 'Paulistas'},
{name: 'Pavão'},
{name: 'Peçanha'},
{name: 'Pedra Azul'},
{name: 'Pedra Bonita'},
{name: 'Pedra do Anta'},
{name: 'Pedra do Indaiá'},
{name: 'Pedra Dourada'},
{name: 'Pedralva'},
{name: 'Pedras de Maria da Cruz'},
{name: 'Pedrinópolis'},
{name: 'Pedro Leopoldo'},
{name: 'Pedro Teixeira'},
{name: 'Pequeri'},
{name: 'Pequi'},
{name: 'Perdigão'},
{name: 'Perdizes'},
{name: 'Perdões'},
{name: 'Periquito'},
{name: 'Pescador'},
{name: 'Piau'},
{name: 'Piedade de Caratinga'},
{name: 'Piedade de Ponte Nova'},
{name: 'Piedade do Rio Grande'},
{name: 'Piedade dos Gerais'},
{name: 'Pimenta'},
{name: 'Pingo-d`Água'},
{name: 'Pintópolis'},
{name: 'Piracema'},
{name: 'Pirajuba'},
{name: 'Piranga'},
{name: 'Piranguçu'},
{name: 'Piranguinho'},
{name: 'Pirapetinga'},
{name: 'Pirapora'},
{name: 'Piraúba'},
{name: 'Pitangui'},
{name: 'Piumhi'},
{name: 'Planura'},
{name: 'Poço Fundo'},
{name: 'Poços de Caldas'},
{name: 'Pocrane'},
{name: 'Pompéu'},
{name: 'Ponte Nova'},
{name: 'Ponto Chique'},
{name: 'Ponto dos Volantes'},
{name: 'Porteirinha'},
{name: 'Porto Firme'},
{name: 'Poté'},
{name: 'Pouso Alegre'},
{name: 'Pouso Alto'},
{name: 'Prados'},
{name: 'Prata'},
{name: 'Pratápolis'},
{name: 'Pratinha'},
{name: 'Presidente Bernardes'},
{name: 'Presidente Juscelino'},
{name: 'Presidente Kubitschek'},
{name: 'Presidente Olegário'},
{name: 'Prudente de Morais'},
{name: 'Quartel Geral'},
{name: 'Queluzito'},
{name: 'Raposos'},
{name: 'Raul Soares'},
{name: 'Recreio'},
{name: 'Reduto'},
{name: 'Resende Costa'},
{name: 'Resplendor'},
{name: 'Ressaquinha'},
{name: 'Riachinho'},
{name: 'Riacho dos Machados'},
{name: 'Ribeirão das Neves'},
{name: 'Ribeirão Vermelho'},
{name: 'Rio Acima'},
{name: 'Rio Casca'},
{name: 'Rio do Prado'},
{name: 'Rio Doce'},
{name: 'Rio Espera'},
{name: 'Rio Manso'},
{name: 'Rio Novo'},
{name: 'Rio Paranaíba'},
{name: 'Rio Pardo de Minas'},
{name: 'Rio Piracicaba'},
{name: 'Rio Pomba'},
{name: 'Rio Preto'},
{name: 'Rio Vermelho'},
{name: 'Ritápolis'},
{name: 'Rochedo de Minas'},
{name: 'Rodeiro'},
{name: 'Romaria'},
{name: 'Rosário da Limeira'},
{name: 'Rubelita'},
{name: 'Rubim'},
{name: 'Sabará'},
{name: 'Sabinópolis'},
{name: 'Sacramento'},
{name: 'Salinas'},
{name: 'Salto da Divisa'},
{name: 'Santa Bárbara'},
{name: 'Santa Bárbara do Leste'},
{name: 'Santa Bárbara do Monte Verde'},
{name: 'Santa Bárbara do Tugúrio'},
{name: 'Santa Cruz de Minas'},
{name: 'Santa Cruz de Salinas'},
{name: 'Santa Cruz do Escalvado'},
{name: 'Santa Efigênia de Minas'},
{name: 'Santa Fé de Minas'},
{name: 'Santa Helena de Minas'},
{name: 'Santa Juliana'},
{name: 'Santa Luzia'},
{name: 'Santa Margarida'},
{name: 'Santa Maria de Itabira'},
{name: 'Santa Maria do Salto'},
{name: 'Santa Maria do Suaçuí'},
{name: 'Santa Rita de Caldas'},
{name: 'Santa Rita de Ibitipoca'},
{name: 'Santa Rita de Jacutinga'},
{name: 'Santa Rita de Minas'},
{name: 'Santa Rita do Itueto'},
{name: 'Santa Rita do Sapucaí'},
{name: 'Santa Rosa da Serra'},
{name: 'Santa Vitória'},
{name: 'Santana da Vargem'},
{name: 'Santana de Cataguases'},
{name: 'Santana de Pirapama'},
{name: 'Santana do Deserto'},
{name: 'Santana do Garambéu'},
{name: 'Santana do Jacaré'},
{name: 'Santana do Manhuaçu'},
{name: 'Santana do Paraíso'},
{name: 'Santana do Riacho'},
{name: 'Santana dos Montes'},
{name: 'Santo Antônio do Amparo'},
{name: 'Santo Antônio do Aventureiro'},
{name: 'Santo Antônio do Grama'},
{name: 'Santo Antônio do Itambé'},
{name: 'Santo Antônio do Jacinto'},
{name: 'Santo Antônio do Monte'},
{name: 'Santo Antônio do Retiro'},
{name: 'Santo Antônio do Rio Abaixo'},
{name: 'Santo Hipólito'},
{name: 'Santos Dumont'},
{name: 'São Bento Abade'},
{name: 'São Brás do Suaçuí'},
{name: 'São Domingos das Dores'},
{name: 'São Domingos do Prata'},
{name: 'São Félix de Minas'},
{name: 'São Francisco'},
{name: 'São Francisco de Paula'},
{name: 'São Francisco de Sales'},
{name: 'São Francisco do Glória'},
{name: 'São Geraldo'},
{name: 'São Geraldo da Piedade'},
{name: 'São Geraldo do Baixio'},
{name: 'São Gonçalo do Abaeté'},
{name: 'São Gonçalo do Pará'},
{name: 'São Gonçalo do Rio Abaixo'},
{name: 'São Gonçalo do Rio Preto'},
{name: 'São Gonçalo do Sapucaí'},
{name: 'São Gotardo'},
{name: 'São João Batista do Glória'},
{name: 'São João da Lagoa'},
{name: 'São João da Mata'},
{name: 'São João da Ponte'},
{name: 'São João das Missões'},
{name: 'São João del Rei'},
{name: 'São João do Manhuaçu'},
{name: 'São João do Manteninha'},
{name: 'São João do Oriente'},
{name: 'São João do Pacuí'},
{name: 'São João do Paraíso'},
{name: 'São João Evangelista'},
{name: 'São João Nepomuceno'},
{name: 'São Joaquim de Bicas'},
{name: 'São José da Barra'},
{name: 'São José da Lapa'},
{name: 'São José da Safira'},
{name: 'São José da Varginha'},
{name: 'São José do Alegre'},
{name: 'São José do Divino'},
{name: 'São José do Goiabal'},
{name: 'São José do Jacuri'},
{name: 'São José do Mantimento'},
{name: 'São Lourenço'},
{name: 'São Miguel do Anta'},
{name: 'São Pedro da União'},
{name: 'São Pedro do Suaçuí'},
{name: 'São Pedro dos Ferros'},
{name: 'São Romão'},
{name: 'São Roque de Minas'},
{name: 'São Sebastião da Bela Vista'},
{name: 'São Sebastião da Vargem Alegre'},
{name: 'São Sebastião do Anta'},
{name: 'São Sebastião do Maranhão'},
{name: 'São Sebastião do Oeste'},
{name: 'São Sebastião do Paraíso'},
{name: 'São Sebastião do Rio Preto'},
{name: 'São Sebastião do Rio Verde'},
{name: 'São Thomé das Letras'},
{name: 'São Tiago'},
{name: 'São Tomás de Aquino'},
{name: 'São Vicente de Minas'},
{name: 'Sapucaí-Mirim'},
{name: 'Sardoá'},
{name: 'Sarzedo'},
{name: 'Sem-Peixe'},
{name: 'Senador Amaral'},
{name: 'Senador Cortes'},
{name: 'Senador Firmino'},
{name: 'Senador José Bento'},
{name: 'Senador Modestino Gonçalves'},
{name: 'Senhora de Oliveira'},
{name: 'Senhora do Porto'},
{name: 'Senhora dos Remédios'},
{name: 'Sericita'},
{name: 'Seritinga'},
{name: 'Serra Azul de Minas'},
{name: 'Serra da Saudade'},
{name: 'Serra do Salitre'},
{name: 'Serra dos Aimorés'},
{name: 'Serrania'},
{name: 'Serranópolis de Minas'},
{name: 'Serranos'},
{name: 'Serro'},
{name: 'Sete Lagoas'},
{name: 'Setubinha'},
{name: 'Silveirânia'},
{name: 'Silvianópolis'},
{name: 'Simão Pereira'},
{name: 'Simonésia'},
{name: 'Sobrália'},
{name: 'Soledade de Minas'},
{name: 'Tabuleiro'},
{name: 'Taiobeiras'},
{name: 'Taparuba'},
{name: 'Tapira'},
{name: 'Tapiraí'},
{name: 'Taquaraçu de Minas'},
{name: 'Tarumirim'},
{name: 'Teixeiras'},
{name: 'Teófilo Otoni'},
{name: 'Timóteo'},
{name: 'Tiradentes'},
{name: 'Tiros'},
{name: 'Tocantins'},
{name: 'Tocos do Moji'},
{name: 'Toledo'},
{name: 'Tombos'},
{name: 'Três Corações'},
{name: 'Três Marias'},
{name: 'Três Pontas'},
{name: 'Tumiritinga'},
{name: 'Tupaciguara'},
{name: 'Turmalina'},
{name: 'Turvolândia'},
{name: 'Ubá'},
{name: 'Ubaí'},
{name: 'Ubaporanga'},
{name: 'Uberaba'},
{name: 'Uberlândia'},
{name: 'Umburatiba'},
{name: 'Unaí'},
{name: 'União de Minas'},
{name: 'Uruana de Minas'},
{name: 'Urucânia'},
{name: 'Urucuia'},
{name: 'Vargem Alegre'},
{name: 'Vargem Bonita'},
{name: 'Vargem Grande do Rio Pardo'},
{name: 'Varginha'},
{name: 'Varjão de Minas'},
{name: 'Várzea da Palma'},
{name: 'Varzelândia'},
{name: 'Vazante'},
{name: 'Verdelândia'},
{name: 'Veredinha'},
{name: 'Veríssimo'},
{name: 'Vermelho Novo'},
{name: 'Vespasiano'},
{name: 'Viçosa'},
{name: 'Vieiras'},
{name: 'Virgem da Lapa'},
{name: 'Virgínia'},
{name: 'Virginópolis'},
{name: 'Virgolândia'},
{name: 'Visconde do Rio Branco'},
{name: 'Volta Grande'},
{name: 'Wenceslau Braz'}];
