module.exports = [{ name: 'Água Clara' },
{ name: 'Alcinópolis' },
{ name: 'Amambaí' },
{ name: 'Anastácio' },
{ name: 'Anaurilândia' },
{ name: 'Angélica' },
{ name: 'Antônio João' },
{ name: 'Aparecida do Taboado' },
{ name: 'Aquidauana' },
{ name: 'Aral Moreira' },
{ name: 'Bandeirantes' },
{ name: 'Bataguassu' },
{ name: 'Bataiporã' },
{ name: 'Bela Vista' },
{ name: 'Bodoquena' },
{ name: 'Bonito' },
{ name: 'Brasilândia' },
{ name: 'Caarapó' },
{ name: 'Camapuã' },
{ name: 'Campo Grande' },
{ name: 'Caracol' },
{ name: 'Cassilândia' },
{ name: 'Chapadão do Sul' },
{ name: 'Corguinho' },
{ name: 'Coronel Sapucaia' },
{ name: 'Corumbá' },
{ name: 'Costa Rica' },
{ name: 'Coxim' },
{ name: 'Deodápolis' },
{ name: 'Dois Irmãos do Buriti' },
{ name: 'Douradina' },
{ name: 'Dourados' },
{ name: 'Eldorado' },
{ name: 'Fátima do Sul' },
{ name: 'Figueirão' },
{ name: 'Glória de Dourados' },
{ name: 'Guia Lopes da Laguna' },
{ name: 'Iguatemi' },
{ name: 'Inocência' },
{ name: 'Itaporã' },
{ name: 'Itaquiraí' },
{ name: 'Ivinhema' },
{ name: 'Japorã' },
{ name: 'Jaraguari' },
{ name: 'Jardim' },
{ name: 'Jateí' },
{ name: 'Juti' },
{ name: 'Ladário' },
{ name: 'Laguna Carapã' },
{ name: 'Maracaju' },
{ name: 'Miranda' },
{ name: 'Mundo Novo' },
{ name: 'Naviraí' },
{ name: 'Nioaque' },
{ name: 'Nova Alvorada do Sul' },
{ name: 'Nova Andradina' },
{ name: 'Novo Horizonte do Sul' },
{ name: 'Paranaíba' },
{ name: 'Paranhos' },
{ name: 'Pedro Gomes' },
{ name: 'Ponta Porã' },
{ name: 'Porto Murtinho' },
{ name: 'Ribas do Rio Pardo' },
{ name: 'Rio Brilhante' },
{ name: 'Rio Negro' },
{ name: 'Rio Verde de Mato Grosso' },
{ name: 'Rochedo' },
{ name: 'Santa Rita do Pardo' },
{ name: 'São Gabriel do Oeste' },
{ name: 'Selvíria' },
{ name: 'Sete Quedas' },
{ name: 'Sidrolândia' },
{ name: 'Sonora' },
{ name: 'Tacuru' },
{ name: 'Taquarussu' },
{ name: 'Terenos' },
{ name: 'Três Lagoas' },
{ name: 'Vicentina' } ];
