module.exports = [{ name: 'Abaetetuba'},
{ name: 'Abel Figueiredo'},
{ name: 'Acará'},
{ name: 'Afuá'},
{ name: 'Água Azul do Norte'},
{ name: 'Alenquer'},
{ name: 'Almeirim'},
{ name: 'Altamira'},
{ name: 'Anajás'},
{ name: 'Ananindeua'},
{ name: 'Anapu'},
{ name: 'Augusto Corrêa'},
{ name: 'Aurora do Pará'},
{ name: 'Aveiro'},
{ name: 'Bagre'},
{ name: 'Baião'},
{ name: 'Bannach'},
{ name: 'Barcarena'},
{ name: 'Belém'},
{ name: 'Belterra'},
{ name: 'Benevides'},
{ name: 'Bom Jesus do Tocantins'},
{ name: 'Bonito'},
{ name: 'Bragança'},
{ name: 'Brasil Novo'},
{ name: 'Brejo Grande do Araguaia'},
{ name: 'Breu Branco'},
{ name: 'Breves'},
{ name: 'Bujaru'},
{ name: 'Cachoeira do Arari'},
{ name: 'Cachoeira do Piriá'},
{ name: 'Cametá'},
{ name: 'Canaã dos Carajás'},
{ name: 'Capanema'},
{ name: 'Capitão Poço'},
{ name: 'Castanhal'},
{ name: 'Chaves'},
{ name: 'Colares'},
{ name: 'Conceição do Araguaia'},
{ name: 'Concórdia do Pará'},
{ name: 'Cumaru do Norte'},
{ name: 'Curionópolis'},
{ name: 'Curralinho'},
{ name: 'Curuá'},
{ name: 'Curuçá'},
{ name: 'Dom Eliseu'},
{ name: 'Eldorado dos Carajás'},
{ name: 'Faro'},
{ name: 'Floresta do Araguaia'},
{ name: 'Garrafão do Norte'},
{ name: 'Goianésia do Pará'},
{ name: 'Gurupá'},
{ name: 'Igarapé-Açu'},
{ name: 'Igarapé-Miri'},
{ name: 'Inhangapi'},
{ name: 'Ipixuna do Pará'},
{ name: 'Irituia'},
{ name: 'Itaituba'},
{ name: 'Itupiranga'},
{ name: 'Jacareacanga'},
{ name: 'Jacundá'},
{ name: 'Juruti'},
{ name: 'Limoeiro do Ajuru'},
{ name: 'Mãe do Rio'},
{ name: 'Magalhães Barata'},
{ name: 'Marabá'},
{ name: 'Maracanã'},
{ name: 'Marapanim'},
{ name: 'Marituba'},
{ name: 'Medicilândia'},
{ name: 'Melgaço'},
{ name: 'Mocajuba'},
{ name: 'Moju'},
{ name: 'Monte Alegre'},
{ name: 'Muaná'},
{ name: 'Nova Esperança do Piriá'},
{ name: 'Nova Ipixuna'},
{ name: 'Nova Timboteua'},
{ name: 'Novo Progresso'},
{ name: 'Novo Repartimento'},
{ name: 'Óbidos'},
{ name: 'Oeiras do Pará'},
{ name: 'Oriximiná'},
{ name: 'Ourém'},
{ name: 'Ourilândia do Norte'},
{ name: 'Pacajá'},
{ name: 'Palestina do Pará'},
{ name: 'Paragominas'},
{ name: 'Parauapebas'},
{ name: 'Pau d`Arco'},
{ name: 'Peixe-Boi'},
{ name: 'Piçarra'},
{ name: 'Placas'},
{ name: 'Ponta de Pedras'},
{ name: 'Portel'},
{ name: 'Porto de Moz'},
{ name: 'Prainha'},
{ name: 'Primavera'},
{ name: 'Quatipuru'},
{ name: 'Redenção'},
{ name: 'Rio Maria'},
{ name: 'Rondon do Pará'},
{ name: 'Rurópolis'},
{ name: 'Salinópolis'},
{ name: 'Salvaterra'},
{ name: 'Santa Bárbara do Pará'},
{ name: 'Santa Cruz do Arari'},
{ name: 'Santa Isabel do Pará'},
{ name: 'Santa Luzia do Pará'},
{ name: 'Santa Maria das Barreiras'},
{ name: 'Santa Maria do Pará'},
{ name: 'Santana do Araguaia'},
{ name: 'Santarém'},
{ name: 'Santarém Novo'},
{ name: 'Santo Antônio do Tauá'},
{ name: 'São Caetano de Odivelas'},
{ name: 'São Domingos do Araguaia'},
{ name: 'São Domingos do Capim'},
{ name: 'São Félix do Xingu'},
{ name: 'São Francisco do Pará'},
{ name: 'São Geraldo do Araguaia'},
{ name: 'São João da Ponta'},
{ name: 'São João de Pirabas'},
{ name: 'São João do Araguaia'},
{ name: 'São Miguel do Guamá'},
{ name: 'São Sebastião da Boa Vista'},
{ name: 'Sapucaia'},
{ name: 'Senador José Porfírio'},
{ name: 'Soure'},
{ name: 'Tailândia'},
{ name: 'Terra Alta'},
{ name: 'Terra Santa'},
{ name: 'Tomé-Açu'},
{ name: 'Tracuateua'},
{ name: 'Trairão'},
{ name: 'Tucumã'},
{ name: 'Tucuruí'},
{ name: 'Ulianópolis'},
{ name: 'Uruará'},
{ name: 'Vigia'},
{ name: 'Viseu'},
{ name: 'Vitória do Xingu'},
{ name: 'Xinguara'}];
