module.exports = [{ name: 'Água Branca'},
{ name: 'Aguiar'},
{ name: 'Alagoa Grande'},
{ name: 'Alagoa Nova'},
{ name: 'Alagoinha'},
{ name: 'Alcantil'},
{ name: 'Algodão de Jandaíra'},
{ name: 'Alhandra'},
{ name: 'Amparo'},
{ name: 'Aparecida'},
{ name: 'Araçagi'},
{ name: 'Arara'},
{ name: 'Araruna'},
{ name: 'Areia'},
{ name: 'Areia de Baraúnas'},
{ name: 'Areial'},
{ name: 'Aroeiras'},
{ name: 'Assunção'},
{ name: 'Baía da Traição'},
{ name: 'Bananeiras'},
{ name: 'Baraúna'},
{ name: 'Barra de Santa Rosa'},
{ name: 'Barra de Santana'},
{ name: 'Barra de São Miguel'},
{ name: 'Bayeux'},
{ name: 'Belém'},
{ name: 'Belém do Brejo do Cruz'},
{ name: 'Bernardino Batista'},
{ name: 'Boa Ventura'},
{ name: 'Boa Vista'},
{ name: 'Bom Jesus'},
{ name: 'Bom Sucesso'},
{ name: 'Bonito de Santa Fé'},
{ name: 'Boqueirão'},
{ name: 'Borborema'},
{ name: 'Brejo do Cruz'},
{ name: 'Brejo dos Santos'},
{ name: 'Caaporã'},
{ name: 'Cabaceiras'},
{ name: 'Cabedelo'},
{ name: 'Cachoeira dos Índios'},
{ name: 'Cacimba de Areia'},
{ name: 'Cacimba de Dentro'},
{ name: 'Cacimbas'},
{ name: 'Caiçara'},
{ name: 'Cajazeiras'},
{ name: 'Cajazeirinhas'},
{ name: 'Caldas Brandão'},
{ name: 'Camalaú'},
{ name: 'Campina Grande'},
{ name: 'Campo de Santana'},
{ name: 'Capim'},
{ name: 'Caraúbas'},
{ name: 'Carrapateira'},
{ name: 'Casserengue'},
{ name: 'Catingueira'},
{ name: 'Catolé do Rocha'},
{ name: 'Caturité'},
{ name: 'Conceição'},
{ name: 'Condado'},
{ name: 'Conde'},
{ name: 'Congo'},
{ name: 'Coremas'},
{ name: 'Coxixola'},
{ name: 'Cruz do Espírito Santo'},
{ name: 'Cubati'},
{ name: 'Cuité'},
{ name: 'Cuité de Mamanguape'},
{ name: 'Cuitegi'},
{ name: 'Curral de Cima'},
{ name: 'Curral Velho'},
{ name: 'Damião'},
{ name: 'Desterro'},
{ name: 'Diamante'},
{ name: 'Dona Inês'},
{ name: 'Duas Estradas'},
{ name: 'Emas'},
{ name: 'Esperança'},
{ name: 'Fagundes'},
{ name: 'Frei Martinho'},
{ name: 'Gado Bravo'},
{ name: 'Guarabira'},
{ name: 'Gurinhém'},
{ name: 'Gurjão'},
{ name: 'Ibiara'},
{ name: 'Igaracy'},
{ name: 'Imaculada'},
{ name: 'Ingá'},
{ name: 'Itabaiana'},
{ name: 'Itaporanga'},
{ name: 'Itapororoca'},
{ name: 'Itatuba'},
{ name: 'Jacaraú'},
{ name: 'Jericó'},
{ name: 'João Pessoa'},
{ name: 'Juarez Távora'},
{ name: 'Juazeirinho'},
{ name: 'Junco do Seridó'},
{ name: 'Juripiranga'},
{ name: 'Juru'},
{ name: 'Lagoa'},
{ name: 'Lagoa de Dentro'},
{ name: 'Lagoa Seca'},
{ name: 'Lastro'},
{ name: 'Livramento'},
{ name: 'Logradouro'},
{ name: 'Lucena'},
{ name: 'Mãe d`Água'},
{ name: 'Malta'},
{ name: 'Mamanguape'},
{ name: 'Manaíra'},
{ name: 'Marcação'},
{ name: 'Mari'},
{ name: 'Marizópolis'},
{ name: 'Massaranduba'},
{ name: 'Mataraca'},
{ name: 'Matinhas'},
{ name: 'Mato Grosso'},
{ name: 'Maturéia'},
{ name: 'Mogeiro'},
{ name: 'Montadas'},
{ name: 'Monte Horebe'},
{ name: 'Monteiro'},
{ name: 'Mulungu'},
{ name: 'Natuba'},
{ name: 'Nazarezinho'},
{ name: 'Nova Floresta'},
{ name: 'Nova Olinda'},
{ name: 'Nova Palmeira'},
{ name: 'Olho d`Água'},
{ name: 'Olivedos'},
{ name: 'Ouro Velho'},
{ name: 'Parari'},
{ name: 'Passagem'},
{ name: 'Patos'},
{ name: 'Paulista'},
{ name: 'Pedra Branca'},
{ name: 'Pedra Lavrada'},
{ name: 'Pedras de Fogo'},
{ name: 'Pedro Régis'},
{ name: 'Piancó'},
{ name: 'Picuí'},
{ name: 'Pilar'},
{ name: 'Pilões'},
{ name: 'Pilõezinhos'},
{ name: 'Pirpirituba'},
{ name: 'Pitimbu'},
{ name: 'Pocinhos'},
{ name: 'Poço Dantas'},
{ name: 'Poço de José de Moura'},
{ name: 'Pombal'},
{ name: 'Prata'},
{ name: 'Princesa Isabel'},
{ name: 'Puxinanã'},
{ name: 'Queimadas'},
{ name: 'Quixabá'},
{ name: 'Remígio'},
{ name: 'Riachão'},
{ name: 'Riachão do Bacamarte'},
{ name: 'Riachão do Poço'},
{ name: 'Riacho de Santo Antônio'},
{ name: 'Riacho dos Cavalos'},
{ name: 'Rio Tinto'},
{ name: 'Salgadinho'},
{ name: 'Salgado de São Félix'},
{ name: 'Santa Cecília'},
{ name: 'Santa Cruz'},
{ name: 'Santa Helena'},
{ name: 'Santa Inês'},
{ name: 'Santa Luzia'},
{ name: 'Santa Rita'},
{ name: 'Santa Teresinha'},
{ name: 'Santana de Mangueira'},
{ name: 'Santana dos Garrotes'},
{ name: 'Santarém'},
{ name: 'Santo André'},
{ name: 'São Bentinho'},
{ name: 'São Bento'},
{ name: 'São Domingos de Pombal'},
{ name: 'São Domingos do Cariri'},
{ name: 'São Francisco'},
{ name: 'São João do Cariri'},
{ name: 'São João do Rio do Peixe'},
{ name: 'São João do Tigre'},
{ name: 'São José da Lagoa Tapada'},
{ name: 'São José de Caiana'},
{ name: 'São José de Espinharas'},
{ name: 'São José de Piranhas'},
{ name: 'São José de Princesa'},
{ name: 'São José do Bonfim'},
{ name: 'São José do Brejo do Cruz'},
{ name: 'São José do Sabugi'},
{ name: 'São José dos Cordeiros'},
{ name: 'São José dos Ramos'},
{ name: 'São Mamede'},
{ name: 'São Miguel de Taipu'},
{ name: 'São Sebastião de Lagoa de Roça'},
{ name: 'São Sebastião do Umbuzeiro'},
{ name: 'Sapé'},
{ name: 'Seridó'},
{ name: 'Serra Branca'},
{ name: 'Serra da Raiz'},
{ name: 'Serra Grande'},
{ name: 'Serra Redonda'},
{ name: 'Serraria'},
{ name: 'Sertãozinho'},
{ name: 'Sobrado'},
{ name: 'Solânea'},
{ name: 'Soledade'},
{ name: 'Sossêgo'},
{ name: 'Sousa'},
{ name: 'Sumé'},
{ name: 'Taperoá'},
{ name: 'Tavares'},
{ name: 'Teixeira'},
{ name: 'Tenório'},
{ name: 'Triunfo'},
{ name: 'Uiraúna'},
{ name: 'Umbuzeiro'},
{ name: 'Várzea'},
{ name: 'Vieirópolis'},
{ name: 'Vista Serrana'},
{ name: 'Zabelê'} ];
