
module.exports = [{ name: 'Abreu e Lima' },
{ name: 'Afogados da Ingazeira' },
{ name: 'Afrânio' },
{ name: 'Agrestina' },
{ name: 'Água Preta' },
{ name: 'Águas Belas' },
{ name: 'Alagoinha' },
{ name: 'Aliança' },
{ name: 'Altinho' },
{ name: 'Amaraji' },
{ name: 'Angelim' },
{ name: 'Araçoiaba' },
{ name: 'Araripina' },
{ name: 'Arcoverde' },
{ name: 'Barra de Guabiraba' },
{ name: 'Barreiros' },
{ name: 'Belém de Maria' },
{ name: 'Belém de São Francisco' },
{ name: 'Belo Jardim' },
{ name: 'Betânia' },
{ name: 'Bezerros' },
{ name: 'Bodocó' },
{ name: 'Bom Conselho' },
{ name: 'Bom Jardim' },
{ name: 'Bonito' },
{ name: 'Brejão' },
{ name: 'Brejinho' },
{ name: 'Brejo da Madre de Deus' },
{ name: 'Buenos Aires' },
{ name: 'Buíque' },
{ name: 'Cabo de Santo Agostinho' },
{ name: 'Cabrobó' },
{ name: 'Cachoeirinha' },
{ name: 'Caetés' },
{ name: 'Calçado' },
{ name: 'Calumbi' },
{ name: 'Camaragibe' },
{ name: 'Camocim de São Félix' },
{ name: 'Camutanga' },
{ name: 'Canhotinho' },
{ name: 'Capoeiras' },
{ name: 'Carnaíba' },
{ name: 'Carnaubeira da Penha' },
{ name: 'Carpina' },
{ name: 'Caruaru' },
{ name: 'Casinhas' },
{ name: 'Catende' },
{ name: 'Cedro' },
{ name: 'Chã de Alegria' },
{ name: 'Chã Grande' },
{ name: 'Condado' },
{ name: 'Correntes' },
{ name: 'Cortês' },
{ name: 'Cumaru' },
{ name: 'Cupira' },
{ name: 'Custódia' },
{ name: 'Dormentes' },
{ name: 'Escada' },
{ name: 'Exu' },
{ name: 'Feira Nova' },
{ name: 'Fernando de Noronha' },
{ name: 'Ferreiros' },
{ name: 'Flores' },
{ name: 'Floresta' },
{ name: 'Frei Miguelinho' },
{ name: 'Gameleira' },
{ name: 'Garanhuns' },
{ name: 'Glória do Goitá' },
{ name: 'Goiana' },
{ name: 'Granito' },
{ name: 'Gravatá' },
{ name: 'Iati' },
{ name: 'Ibimirim' },
{ name: 'Ibirajuba' },
{ name: 'Igarassu' },
{ name: 'Iguaraci' },
{ name: 'Ilha de Itamaracá' },
{ name: 'Inajá' },
{ name: 'Ingazeira' },
{ name: 'Ipojuca' },
{ name: 'Ipubi' },
{ name: 'Itacuruba' },
{ name: 'Itaíba' },
{ name: 'Itambé' },
{ name: 'Itapetim' },
{ name: 'Itapissuma' },
{ name: 'Itaquitinga' },
{ name: 'Jaboatão dos Guararapes' },
{ name: 'Jaqueira' },
{ name: 'Jataúba' },
{ name: 'Jatobá' },
{ name: 'João Alfredo' },
{ name: 'Joaquim Nabuco' },
{ name: 'Jucati' },
{ name: 'Jupi' },
{ name: 'Jurema' },
{ name: 'Lagoa do Carro' },
{ name: 'Lagoa do Itaenga' },
{ name: 'Lagoa do Ouro' },
{ name: 'Lagoa dos Gatos' },
{ name: 'Lagoa Grande' },
{ name: 'Lajedo' },
{ name: 'Limoeiro' },
{ name: 'Macaparana' },
{ name: 'Machados' },
{ name: 'Manari' },
{ name: 'Maraial' },
{ name: 'Mirandiba' },
{ name: 'Moreilândia' },
{ name: 'Moreno' },
{ name: 'Nazaré da Mata' },
{ name: 'Olinda' },
{ name: 'Orobó' },
{ name: 'Orocó' },
{ name: 'Ouricuri' },
{ name: 'Palmares' },
{ name: 'Palmeirina' },
{ name: 'Panelas' },
{ name: 'Paranatama' },
{ name: 'Parnamirim' },
{ name: 'Passira' },
{ name: 'Paudalho' },
{ name: 'Paulista' },
{ name: 'Pedra' },
{ name: 'Pesqueira' },
{ name: 'Petrolândia' },
{ name: 'Petrolina' },
{ name: 'Poção' },
{ name: 'Pombos' },
{ name: 'Primavera' },
{ name: 'Quipapá' },
{ name: 'Quixaba' },
{ name: 'Recife' },
{ name: 'Riacho das Almas' },
{ name: 'Ribeirão' },
{ name: 'Rio Formoso' },
{ name: 'Sairé' },
{ name: 'Salgadinho' },
{ name: 'Salgueiro' },
{ name: 'Saloá' },
{ name: 'Sanharó' },
{ name: 'Santa Cruz' },
{ name: 'Santa Cruz da Baixa Verde' },
{ name: 'Santa Cruz do Capibaribe' },
{ name: 'Santa Filomena' },
{ name: 'Santa Maria da Boa Vista' },
{ name: 'Santa Maria do Cambucá' },
{ name: 'Santa Terezinha' },
{ name: 'São Benedito do Sul' },
{ name: 'São Bento do Una' },
{ name: 'São Caitano' },
{ name: 'São João' },
{ name: 'São Joaquim do Monte' },
{ name: 'São José da Coroa Grande' },
{ name: 'São José do Belmonte' },
{ name: 'São José do Egito' },
{ name: 'São Lourenço da Mata' },
{ name: 'São Vicente Ferrer' },
{ name: 'Serra Talhada' },
{ name: 'Serrita' },
{ name: 'Sertânia' },
{ name: 'Sirinhaém' },
{ name: 'Solidão' },
{ name: 'Surubim' },
{ name: 'Tabira' },
{ name: 'Tacaimbó' },
{ name: 'Tacaratu' },
{ name: 'Tamandaré' },
{ name: 'Taquaritinga do Norte' },
{ name: 'Terezinha' },
{ name: 'Terra Nova' },
{ name: 'Timbaúba' },
{ name: 'Toritama' },
{ name: 'Tracunhaém' },
{ name: 'Trindade' },
{ name: 'Triunfo' },
{ name: 'Tupanatinga' },
{ name: 'Tuparetama' },
{ name: 'Venturosa' },
{ name: 'Verdejante' },
{ name: 'Vertente do Lério' },
{ name: 'Vertentes' },
{ name: 'Vicência' },
{ name: 'Vitória de Santo Antão' },
{ name: 'Xexéu' }];
