module.exports = [{ name: 'Acauã'}, 
{ name: 'Agricolândia'}, 
{ name: 'Água Branca'}, 
{ name: 'Alagoinha do Piauí'}, 
{ name: 'Alegrete do Piauí'}, 
{ name: 'Alto Longá'}, 
{ name: 'Altos'}, 
{ name: 'Alvorada do Gurguéia'}, 
{ name: 'Amarante'}, 
{ name: 'Angical do Piauí'}, 
{ name: 'Anísio de Abreu'}, 
{ name: 'Antônio Almeida'}, 
{ name: 'Aroazes'}, 
{ name: 'Aroeiras do Itaim'}, 
{ name: 'Arraial'}, 
{ name: 'Assunção do Piauí'}, 
{ name: 'Avelino Lopes'}, 
{ name: 'Baixa Grande do Ribeiro'}, 
{ name: 'Barra d`Alcântara'}, 
{ name: 'Barras'}, 
{ name: 'Barreiras do Piauí'}, 
{ name: 'Barro Duro'}, 
{ name: 'Batalha'}, 
{ name: 'Bela Vista do Piauí'}, 
{ name: 'Belém do Piauí'}, 
{ name: 'Beneditinos'}, 
{ name: 'Bertolínia'}, 
{ name: 'Betânia do Piauí'}, 
{ name: 'Boa Hora'}, 
{ name: 'Bocaina'}, 
{ name: 'Bom Jesus'}, 
{ name: 'Bom Princípio do Piauí'}, 
{ name: 'Bonfim do Piauí'}, 
{ name: 'Boqueirão do Piauí'}, 
{ name: 'Brasileira'}, 
{ name: 'Brejo do Piauí'}, 
{ name: 'Buriti dos Lopes'}, 
{ name: 'Buriti dos Montes'}, 
{ name: 'Cabeceiras do Piauí'}, 
{ name: 'Cajazeiras do Piauí'}, 
{ name: 'Cajueiro da Praia'}, 
{ name: 'Caldeirão Grande do Piauí'}, 
{ name: 'Campinas do Piauí'}, 
{ name: 'Campo Alegre do Fidalgo'}, 
{ name: 'Campo Grande do Piauí'}, 
{ name: 'Campo Largo do Piauí'}, 
{ name: 'Campo Maior'}, 
{ name: 'Canavieira'}, 
{ name: 'Canto do Buriti'}, 
{ name: 'Capitão de Campos'}, 
{ name: 'Capitão Gervásio Oliveira'}, 
{ name: 'Caracol'}, 
{ name: 'Caraúbas do Piauí'}, 
{ name: 'Caridade do Piauí'}, 
{ name: 'Castelo do Piauí'}, 
{ name: 'Caxingó'}, 
{ name: 'Cocal'}, 
{ name: 'Cocal de Telha'}, 
{ name: 'Cocal dos Alves'}, 
{ name: 'Coivaras'}, 
{ name: 'Colônia do Gurguéia'}, 
{ name: 'Colônia do Piauí'}, 
{ name: 'Conceição do Canindé'}, 
{ name: 'Coronel José Dias'}, 
{ name: 'Corrente'}, 
{ name: 'Cristalândia do Piauí'}, 
{ name: 'Cristino Castro'}, 
{ name: 'Curimatá'}, 
{ name: 'Currais'}, 
{ name: 'Curral Novo do Piauí'}, 
{ name: 'Curralinhos'}, 
{ name: 'Demerval Lobão'}, 
{ name: 'Dirceu Arcoverde'}, 
{ name: 'Dom Expedito Lopes'}, 
{ name: 'Dom Inocêncio'}, 
{ name: 'Domingos Mourão'}, 
{ name: 'Elesbão Veloso'}, 
{ name: 'Eliseu Martins'}, 
{ name: 'Esperantina'}, 
{ name: 'Fartura do Piauí'}, 
{ name: 'Flores do Piauí'}, 
{ name: 'Floresta do Piauí'}, 
{ name: 'Floriano'}, 
{ name: 'Francinópolis'}, 
{ name: 'Francisco Ayres'}, 
{ name: 'Francisco Macedo'}, 
{ name: 'Francisco Santos'}, 
{ name: 'Fronteiras'}, 
{ name: 'Geminiano'}, 
{ name: 'Gilbués'}, 
{ name: 'Guadalupe'}, 
{ name: 'Guaribas'}, 
{ name: 'Hugo Napoleão'}, 
{ name: 'Ilha Grande'}, 
{ name: 'Inhuma'}, 
{ name: 'Ipiranga do Piauí'}, 
{ name: 'Isaías Coelho'}, 
{ name: 'Itainópolis'}, 
{ name: 'Itaueira'}, 
{ name: 'Jacobina do Piauí'}, 
{ name: 'Jaicós'}, 
{ name: 'Jardim do Mulato'}, 
{ name: 'Jatobá do Piauí'}, 
{ name: 'Jerumenha'}, 
{ name: 'João Costa'}, 
{ name: 'Joaquim Pires'}, 
{ name: 'Joca Marques'}, 
{ name: 'José de Freitas'}, 
{ name: 'Juazeiro do Piauí'}, 
{ name: 'Júlio Borges'}, 
{ name: 'Jurema'}, 
{ name: 'Lagoa Alegre'}, 
{ name: 'Lagoa de São Francisco'}, 
{ name: 'Lagoa do Barro do Piauí'}, 
{ name: 'Lagoa do Piauí'}, 
{ name: 'Lagoa do Sítio'}, 
{ name: 'Lagoinha do Piauí'}, 
{ name: 'Landri Sales'}, 
{ name: 'Luís Correia'}, 
{ name: 'Luzilândia'}, 
{ name: 'Madeiro'}, 
{ name: 'Manoel Emídio'}, 
{ name: 'Marcolândia'}, 
{ name: 'Marcos Parente'}, 
{ name: 'Massapê do Piauí'}, 
{ name: 'Matias Olímpio'}, 
{ name: 'Miguel Alves'}, 
{ name: 'Miguel Leão'}, 
{ name: 'Milton Brandão'}, 
{ name: 'Monsenhor Gil'}, 
{ name: 'Monsenhor Hipólito'}, 
{ name: 'Monte Alegre do Piauí'}, 
{ name: 'Morro Cabeça no Tempo'}, 
{ name: 'Morro do Chapéu do Piauí'}, 
{ name: 'Murici dos Portelas'}, 
{ name: 'Nazaré do Piauí'}, 
{ name: 'Nossa Senhora de Nazaré'}, 
{ name: 'Nossa Senhora dos Remédios'}, 
{ name: 'Nova Santa Rita'}, 
{ name: 'Novo Oriente do Piauí'}, 
{ name: 'Novo Santo Antônio'}, 
{ name: 'Oeiras'}, 
{ name: 'Olho d`Água do Piauí'}, 
{ name: 'Padre Marcos'}, 
{ name: 'Paes Landim'}, 
{ name: 'Pajeú do Piauí'}, 
{ name: 'Palmeira do Piauí'}, 
{ name: 'Palmeirais'}, 
{ name: 'Paquetá'}, 
{ name: 'Parnaguá'}, 
{ name: 'Parnaíba'}, 
{ name: 'Passagem Franca do Piauí'}, 
{ name: 'Patos do Piauí'}, 
{ name: 'Pau d`Arco do Piauí'}, 
{ name: 'Paulistana'}, 
{ name: 'Pavussu'}, 
{ name: 'Pedro II'}, 
{ name: 'Pedro Laurentino'}, 
{ name: 'Picos'}, 
{ name: 'Pimenteiras'}, 
{ name: 'Pio IX'}, 
{ name: 'Piracuruca'}, 
{ name: 'Piripiri'}, 
{ name: 'Porto'}, 
{ name: 'Porto Alegre do Piauí'}, 
{ name: 'Prata do Piauí'}, 
{ name: 'Queimada Nova'}, 
{ name: 'Redenção do Gurguéia'}, 
{ name: 'Regeneração'}, 
{ name: 'Riacho Frio'}, 
{ name: 'Ribeira do Piauí'}, 
{ name: 'Ribeiro Gonçalves'}, 
{ name: 'Rio Grande do Piauí'}, 
{ name: 'Santa Cruz do Piauí'}, 
{ name: 'Santa Cruz dos Milagres'}, 
{ name: 'Santa Filomena'}, 
{ name: 'Santa Luz'}, 
{ name: 'Santa Rosa do Piauí'}, 
{ name: 'Santana do Piauí'}, 
{ name: 'Santo Antônio de Lisboa'}, 
{ name: 'Santo Antônio dos Milagres'}, 
{ name: 'Santo Inácio do Piauí'}, 
{ name: 'São Braz do Piauí'}, 
{ name: 'São Félix do Piauí'}, 
{ name: 'São Francisco de Assis do Piauí'}, 
{ name: 'São Francisco do Piauí'}, 
{ name: 'São Gonçalo do Gurguéia'}, 
{ name: 'São Gonçalo do Piauí'}, 
{ name: 'São João da Canabrava'}, 
{ name: 'São João da Fronteira'}, 
{ name: 'São João da Serra'}, 
{ name: 'São João da Varjota'}, 
{ name: 'São João do Arraial'}, 
{ name: 'São João do Piauí'}, 
{ name: 'São José do Divino'}, 
{ name: 'São José do Peixe'}, 
{ name: 'São José do Piauí'}, 
{ name: 'São Julião'}, 
{ name: 'São Lourenço do Piauí'}, 
{ name: 'São Luis do Piauí'}, 
{ name: 'São Miguel da Baixa Grande'}, 
{ name: 'São Miguel do Fidalgo'}, 
{ name: 'São Miguel do Tapuio'}, 
{ name: 'São Pedro do Piauí'}, 
{ name: 'São Raimundo Nonato'}, 
{ name: 'Sebastião Barros'}, 
{ name: 'Sebastião Leal'}, 
{ name: 'Sigefredo Pacheco'}, 
{ name: 'Simões'}, 
{ name: 'Simplício Mendes'}, 
{ name: 'Socorro do Piauí'}, 
{ name: 'Sussuapara'}, 
{ name: 'Tamboril do Piauí'}, 
{ name: 'Tanque do Piauí'}, 
{ name: 'Teresina'}, 
{ name: 'União'}, 
{ name: 'Uruçuí'}, 
{ name: 'Valença do Piauí'}, 
{ name: 'Várzea Branca'}, 
{ name: 'Várzea Grande'}, 
{ name: 'Vera Mendes'}, 
{ name: 'Vila Nova do Piauí'}, 
{ name: 'Wall Ferraz'}];
