module.exports = [{ name: 'Abatiá'},
{ name: 'Adrianópolis'},
{ name: 'Agudos do Sul'},
{ name: 'Almirante Tamandaré'},
{ name: 'Altamira do Paraná'},
{ name: 'Alto Paraíso'},
{ name: 'Alto Paraná'},
{ name: 'Alto Piquiri'},
{ name: 'Altônia'},
{ name: 'Alvorada do Sul'},
{ name: 'Amaporã'},
{ name: 'Ampére'},
{ name: 'Anahy'},
{ name: 'Andirá'},
{ name: 'Ângulo'},
{ name: 'Antonina'},
{ name: 'Antônio Olinto'},
{ name: 'Apucarana'},
{ name: 'Arapongas'},
{ name: 'Arapoti'},
{ name: 'Arapuã'},
{ name: 'Araruna'},
{ name: 'Araucária'},
{ name: 'Ariranha do Ivaí'},
{ name: 'Assaí'},
{ name: 'Assis Chateaubriand'},
{ name: 'Astorga'},
{ name: 'Atalaia'},
{ name: 'Balsa Nova'},
{ name: 'Bandeirantes'},
{ name: 'Barbosa Ferraz'},
{ name: 'Barra do Jacaré'},
{ name: 'Barracão'},
{ name: 'Bela Vista da Caroba'},
{ name: 'Bela Vista do Paraíso'},
{ name: 'Bituruna'},
{ name: 'Boa Esperança'},
{ name: 'Boa Esperança do Iguaçu'},
{ name: 'Boa Ventura de São Roque'},
{ name: 'Boa Vista da Aparecida'},
{ name: 'Bocaiúva do Sul'},
{ name: 'Bom Jesus do Sul'},
{ name: 'Bom Sucesso'},
{ name: 'Bom Sucesso do Sul'},
{ name: 'Borrazópolis'},
{ name: 'Braganey'},
{ name: 'Brasilândia do Sul'},
{ name: 'Cafeara'},
{ name: 'Cafelândia'},
{ name: 'Cafezal do Sul'},
{ name: 'Califórnia'},
{ name: 'Cambará'},
{ name: 'Cambé'},
{ name: 'Cambira'},
{ name: 'Campina da Lagoa'},
{ name: 'Campina do Simão'},
{ name: 'Campina Grande do Sul'},
{ name: 'Campo Bonito'},
{ name: 'Campo do Tenente'},
{ name: 'Campo Largo'},
{ name: 'Campo Magro'},
{ name: 'Campo Mourão'},
{ name: 'Cândido de Abreu'},
{ name: 'Candói'},
{ name: 'Cantagalo'},
{ name: 'Capanema'},
{ name: 'Capitão Leônidas Marques'},
{ name: 'Carambeí'},
{ name: 'Carlópolis'},
{ name: 'Cascavel'},
{ name: 'Castro'},
{ name: 'Catanduvas'},
{ name: 'Centenário do Sul'},
{ name: 'Cerro Azul'},
{ name: 'Céu Azul'},
{ name: 'Chopinzinho'},
{ name: 'Cianorte'},
{ name: 'Cidade Gaúcha'},
{ name: 'Clevelândia'},
{ name: 'Colombo'},
{ name: 'Colorado'},
{ name: 'Congonhinhas'},
{ name: 'Conselheiro Mairinck'},
{ name: 'Contenda'},
{ name: 'Corbélia'},
{ name: 'Cornélio Procópio'},
{ name: 'Coronel Domingos Soares'},
{ name: 'Coronel Vivida'},
{ name: 'Corumbataí do Sul'},
{ name: 'Cruz Machado'},
{ name: 'Cruzeiro do Iguaçu'},
{ name: 'Cruzeiro do Oeste'},
{ name: 'Cruzeiro do Sul'},
{ name: 'Cruzmaltina'},
{ name: 'Curitiba'},
{ name: 'Curiúva'},
{ name: 'Diamante d`Oeste'},
{ name: 'Diamante do Norte'},
{ name: 'Diamante do Sul'},
{ name: 'Dois Vizinhos'},
{ name: 'Douradina'},
{ name: 'Doutor Camargo'},
{ name: 'Doutor Ulysses'},
{ name: 'Enéas Marques'},
{ name: 'Engenheiro Beltrão'},
{ name: 'Entre Rios do Oeste'},
{ name: 'Esperança Nova'},
{ name: 'Espigão Alto do Iguaçu'},
{ name: 'Farol'},
{ name: 'Faxinal'},
{ name: 'Fazenda Rio Grande'},
{ name: 'Fênix'},
{ name: 'Fernandes Pinheiro'},
{ name: 'Figueira'},
{ name: 'Flor da Serra do Sul'},
{ name: 'Floraí'},
{ name: 'Floresta'},
{ name: 'Florestópolis'},
{ name: 'Flórida'},
{ name: 'Formosa do Oeste'},
{ name: 'Foz do Iguaçu'},
{ name: 'Foz do Jordão'},
{ name: 'Francisco Alves'},
{ name: 'Francisco Beltrão'},
{ name: 'General Carneiro'},
{ name: 'Godoy Moreira'},
{ name: 'Goioerê'},
{ name: 'Goioxim'},
{ name: 'Grandes Rios'},
{ name: 'Guaíra'},
{ name: 'Guairaçá'},
{ name: 'Guamiranga'},
{ name: 'Guapirama'},
{ name: 'Guaporema'},
{ name: 'Guaraci'},
{ name: 'Guaraniaçu'},
{ name: 'Guarapuava'},
{ name: 'Guaraqueçaba'},
{ name: 'Guaratuba'},
{ name: 'Honório Serpa'},
{ name: 'Ibaiti'},
{ name: 'Ibema'},
{ name: 'Ibiporã'},
{ name: 'Icaraíma'},
{ name: 'Iguaraçu'},
{ name: 'Iguatu'},
{ name: 'Imbaú'},
{ name: 'Imbituva'},
{ name: 'Inácio Martins'},
{ name: 'Inajá'},
{ name: 'Indianópolis'},
{ name: 'Ipiranga'},
{ name: 'Iporã'},
{ name: 'Iracema do Oeste'},
{ name: 'Irati'},
{ name: 'Iretama'},
{ name: 'Itaguajé'},
{ name: 'Itaipulândia'},
{ name: 'Itambaracá'},
{ name: 'Itambé'},
{ name: 'Itapejara d`Oeste'},
{ name: 'Itaperuçu'},
{ name: 'Itaúna do Sul'},
{ name: 'Ivaí'},
{ name: 'Ivaiporã'},
{ name: 'Ivaté'},
{ name: 'Ivatuba'},
{ name: 'Jaboti'},
{ name: 'Jacarezinho'},
{ name: 'Jaguapitã'},
{ name: 'Jaguariaíva'},
{ name: 'Jandaia do Sul'},
{ name: 'Janiópolis'},
{ name: 'Japira'},
{ name: 'Japurá'},
{ name: 'Jardim Alegre'},
{ name: 'Jardim Olinda'},
{ name: 'Jataizinho'},
{ name: 'Jesuítas'},
{ name: 'Joaquim Távora'},
{ name: 'Jundiaí do Sul'},
{ name: 'Juranda'},
{ name: 'Jussara'},
{ name: 'Kaloré'},
{ name: 'Lapa'},
{ name: 'Laranjal'},
{ name: 'Laranjeiras do Sul'},
{ name: 'Leópolis'},
{ name: 'Lidianópolis'},
{ name: 'Lindoeste'},
{ name: 'Loanda'},
{ name: 'Lobato'},
{ name: 'Londrina'},
{ name: 'Luiziana'},
{ name: 'Lunardelli'},
{ name: 'Lupionópolis'},
{ name: 'Mallet'},
{ name: 'Mamborê'},
{ name: 'Mandaguaçu'},
{ name: 'Mandaguari'},
{ name: 'Mandirituba'},
{ name: 'Manfrinópolis'},
{ name: 'Mangueirinha'},
{ name: 'Manoel Ribas'},
{ name: 'Marechal Cândido Rondon'},
{ name: 'Maria Helena'},
{ name: 'Marialva'},
{ name: 'Marilândia do Sul'},
{ name: 'Marilena'},
{ name: 'Mariluz'},
{ name: 'Maringá'},
{ name: 'Mariópolis'},
{ name: 'Maripá'},
{ name: 'Marmeleiro'},
{ name: 'Marquinho'},
{ name: 'Marumbi'},
{ name: 'Matelândia'},
{ name: 'Matinhos'},
{ name: 'Mato Rico'},
{ name: 'Mauá da Serra'},
{ name: 'Medianeira'},
{ name: 'Mercedes'},
{ name: 'Mirador'},
{ name: 'Miraselva'},
{ name: 'Missal'},
{ name: 'Moreira Sales'},
{ name: 'Morretes'},
{ name: 'Munhoz de Melo'},
{ name: 'Nossa Senhora das Graças'},
{ name: 'Nova Aliança do Ivaí'},
{ name: 'Nova América da Colina'},
{ name: 'Nova Aurora'},
{ name: 'Nova Cantu'},
{ name: 'Nova Esperança'},
{ name: 'Nova Esperança do Sudoeste'},
{ name: 'Nova Fátima'},
{ name: 'Nova Laranjeiras'},
{ name: 'Nova Londrina'},
{ name: 'Nova Olímpia'},
{ name: 'Nova Prata do Iguaçu'},
{ name: 'Nova Santa Bárbara'},
{ name: 'Nova Santa Rosa'},
{ name: 'Nova Tebas'},
{ name: 'Novo Itacolomi'},
{ name: 'Ortigueira'},
{ name: 'Ourizona'},
{ name: 'Ouro Verde do Oeste'},
{ name: 'Paiçandu'},
{ name: 'Palmas'},
{ name: 'Palmeira'},
{ name: 'Palmital'},
{ name: 'Palotina'},
{ name: 'Paraíso do Norte'},
{ name: 'Paranacity'},
{ name: 'Paranaguá'},
{ name: 'Paranapoema'},
{ name: 'Paranavaí'},
{ name: 'Pato Bragado'},
{ name: 'Pato Branco'},
{ name: 'Paula Freitas'},
{ name: 'Paulo Frontin'},
{ name: 'Peabiru'},
{ name: 'Perobal'},
{ name: 'Pérola'},
{ name: 'Pérola d`Oeste'},
{ name: 'Piên'},
{ name: 'Pinhais'},
{ name: 'Pinhal de São Bento'},
{ name: 'Pinhalão'},
{ name: 'Pinhão'},
{ name: 'Piraí do Sul'},
{ name: 'Piraquara'},
{ name: 'Pitanga'},
{ name: 'Pitangueiras'},
{ name: 'Planaltina do Paraná'},
{ name: 'Planalto'},
{ name: 'Ponta Grossa'},
{ name: 'Pontal do Paraná'},
{ name: 'Porecatu'},
{ name: 'Porto Amazonas'},
{ name: 'Porto Barreiro'},
{ name: 'Porto Rico'},
{ name: 'Porto Vitória'},
{ name: 'Prado Ferreira'},
{ name: 'Pranchita'},
{ name: 'Presidente Castelo Branco'},
{ name: 'Primeiro de Maio'},
{ name: 'Prudentópolis'},
{ name: 'Quarto Centenário'},
{ name: 'Quatiguá'},
{ name: 'Quatro Barras'},
{ name: 'Quatro Pontes'},
{ name: 'Quedas do Iguaçu'},
{ name: 'Querência do Norte'},
{ name: 'Quinta do Sol'},
{ name: 'Quitandinha'},
{ name: 'Ramilândia'},
{ name: 'Rancho Alegre'},
{ name: 'Rancho Alegre d`Oeste'},
{ name: 'Realeza'},
{ name: 'Rebouças'},
{ name: 'Renascença'},
{ name: 'Reserva'},
{ name: 'Reserva do Iguaçu'},
{ name: 'Ribeirão Claro'},
{ name: 'Ribeirão do Pinhal'},
{ name: 'Rio Azul'},
{ name: 'Rio Bom'},
{ name: 'Rio Bonito do Iguaçu'},
{ name: 'Rio Branco do Ivaí'},
{ name: 'Rio Branco do Sul'},
{ name: 'Rio Negro'},
{ name: 'Rolândia'},
{ name: 'Roncador'},
{ name: 'Rondon'},
{ name: 'Rosário do Ivaí'},
{ name: 'Sabáudia'},
{ name: 'Salgado Filho'},
{ name: 'Salto do Itararé'},
{ name: 'Salto do Lontra'},
{ name: 'Santa Amélia'},
{ name: 'Santa Cecília do Pavão'},
{ name: 'Santa Cruz de Monte Castelo'},
{ name: 'Santa Fé'},
{ name: 'Santa Helena'},
{ name: 'Santa Inês'},
{ name: 'Santa Isabel do Ivaí'},
{ name: 'Santa Izabel do Oeste'},
{ name: 'Santa Lúcia'},
{ name: 'Santa Maria do Oeste'},
{ name: 'Santa Mariana'},
{ name: 'Santa Mônica'},
{ name: 'Santa Tereza do Oeste'},
{ name: 'Santa Terezinha de Itaipu'},
{ name: 'Santana do Itararé'},
{ name: 'Santo Antônio da Platina'},
{ name: 'Santo Antônio do Caiuá'},
{ name: 'Santo Antônio do Paraíso'},
{ name: 'Santo Antônio do Sudoeste'},
{ name: 'Santo Inácio'},
{ name: 'São Carlos do Ivaí'},
{ name: 'São Jerônimo da Serra'},
{ name: 'São João'},
{ name: 'São João do Caiuá'},
{ name: 'São João do Ivaí'},
{ name: 'São João do Triunfo'},
{ name: 'São Jorge d`Oeste'},
{ name: 'São Jorge do Ivaí'},
{ name: 'São Jorge do Patrocínio'},
{ name: 'São José da Boa Vista'},
{ name: 'São José das Palmeiras'},
{ name: 'São José dos Pinhais'},
{ name: 'São Manoel do Paraná'},
{ name: 'São Mateus do Sul'},
{ name: 'São Miguel do Iguaçu'},
{ name: 'São Pedro do Iguaçu'},
{ name: 'São Pedro do Ivaí'},
{ name: 'São Pedro do Paraná'},
{ name: 'São Sebastião da Amoreira'},
{ name: 'São Tomé'},
{ name: 'Sapopema'},
{ name: 'Sarandi'},
{ name: 'Saudade do Iguaçu'},
{ name: 'Sengés'},
{ name: 'Serranópolis do Iguaçu'},
{ name: 'Sertaneja'},
{ name: 'Sertanópolis'},
{ name: 'Siqueira Campos'},
{ name: 'Sulina'},
{ name: 'Tamarana'},
{ name: 'Tamboara'},
{ name: 'Tapejara'},
{ name: 'Tapira'},
{ name: 'Teixeira Soares'},
{ name: 'Telêmaco Borba'},
{ name: 'Terra Boa'},
{ name: 'Terra Rica'},
{ name: 'Terra Roxa'},
{ name: 'Tibagi'},
{ name: 'Tijucas do Sul'},
{ name: 'Toledo'},
{ name: 'Tomazina'},
{ name: 'Três Barras do Paraná'},
{ name: 'Tunas do Paraná'},
{ name: 'Tuneiras do Oeste'},
{ name: 'Tupãssi'},
{ name: 'Turvo'},
{ name: 'Ubiratã'},
{ name: 'Umuarama'},
{ name: 'União da Vitória'},
{ name: 'Uniflor'},
{ name: 'Uraí'},
{ name: 'Ventania'},
{ name: 'Vera Cruz do Oeste'},
{ name: 'Verê'},
{ name: 'Virmond'},
{ name: 'Vitorino'},
{ name: 'Wenceslau Braz'},
{ name: 'Xambrê'}];
