module.exports = [
{ name: 'Acari'},
{ name: 'Açu'},
{ name: 'Afonso Bezerra'},
{ name: 'Água Nova'},
{ name: 'Alexandria'},
{ name: 'Almino Afonso'},
{ name: 'Alto do Rodrigues'},
{ name: 'Angicos'},
{ name: 'Antônio Martins'},
{ name: 'Apodi'},
{ name: 'Areia Branca'},
{ name: 'Arês'},
{ name: 'Augusto Severo'},
{ name: 'Baía Formosa'},
{ name: 'Baraúna'},
{ name: 'Barcelona'},
{ name: 'Bento Fernandes'},
{ name: 'Bodó'},
{ name: 'Bom Jesus'},
{ name: 'Brejinho'},
{ name: 'Caiçara do Norte'},
{ name: 'Caiçara do Rio do Vento'},
{ name: 'Caicó'},
{ name: 'Campo Redondo'},
{ name: 'Canguaretama'},
{ name: 'Caraúbas'},
{ name: 'Carnaúba dos Dantas'},
{ name: 'Carnaubais'},
{ name: 'Ceará-Mirim'},
{ name: 'Cerro Corá'},
{ name: 'Coronel Ezequiel'},
{ name: 'Coronel João Pessoa'},
{ name: 'Cruzeta'},
{ name: 'Currais Novos'},
{ name: 'Doutor Severiano'},
{ name: 'Encanto'},
{ name: 'Equador'},
{ name: 'Espírito Santo'},
{ name: 'Extremoz'},
{ name: 'Felipe Guerra'},
{ name: 'Fernando Pedroza'},
{ name: 'Florânia'},
{ name: 'Francisco Dantas'},
{ name: 'Frutuoso Gomes'},
{ name: 'Galinhos'},
{ name: 'Goianinha'},
{ name: 'Governador Dix-Sept Rosado'},
{ name: 'Grossos'},
{ name: 'Guamaré'},
{ name: 'Ielmo Marinho'},
{ name: 'Ipanguaçu'},
{ name: 'Ipueira'},
{ name: 'Itajá'},
{ name: 'Itaú'},
{ name: 'Jaçanã'},
{ name: 'Jandaíra'},
{ name: 'Janduís'},
{ name: 'Januário Cicco'},
{ name: 'Japi'},
{ name: 'Jardim de Angicos'},
{ name: 'Jardim de Piranhas'},
{ name: 'Jardim do Seridó'},
{ name: 'João Câmara'},
{ name: 'João Dias'},
{ name: 'José da Penha'},
{ name: 'Jucurutu'},
{ name: 'Jundiá'},
{ name: 'Lagoa d`Anta'},
{ name: 'Lagoa de Pedras'},
{ name: 'Lagoa de Velhos'},
{ name: 'Lagoa Nova'},
{ name: 'Lagoa Salgada'},
{ name: 'Lajes'},
{ name: 'Lajes Pintadas'},
{ name: 'Lucrécia'},
{ name: 'Luís Gomes'},
{ name: 'Macaíba'},
{ name: 'Macau'},
{ name: 'Major Sales'},
{ name: 'Marcelino Vieira'},
{ name: 'Martins'},
{ name: 'Maxaranguape'},
{ name: 'Messias Targino'},
{ name: 'Montanhas'},
{ name: 'Monte Alegre'},
{ name: 'Monte das Gameleiras'},
{ name: 'Mossoró'},
{ name: 'Natal'},
{ name: 'Nísia Floresta'},
{ name: 'Nova Cruz'},
{ name: 'Olho-d`Água do Borges'},
{ name: 'Ouro Branco'},
{ name: 'Paraná'},
{ name: 'Paraú'},
{ name: 'Parazinho'},
{ name: 'Parelhas'},
{ name: 'Parnamirim'},
{ name: 'Passa e Fica'},
{ name: 'Passagem'},
{ name: 'Patu'},
{ name: 'Pau dos Ferros'},
{ name: 'Pedra Grande'},
{ name: 'Pedra Preta'},
{ name: 'Pedro Avelino'},
{ name: 'Pedro Velho'},
{ name: 'Pendências'},
{ name: 'Pilões'},
{ name: 'Poço Branco'},
{ name: 'Portalegre'},
{ name: 'Porto do Mangue'},
{ name: 'Presidente Juscelino'},
{ name: 'Pureza'},
{ name: 'Rafael Fernandes'},
{ name: 'Rafael Godeiro'},
{ name: 'Riacho da Cruz'},
{ name: 'Riacho de Santana'},
{ name: 'Riachuelo'},
{ name: 'Rio do Fogo'},
{ name: 'Rodolfo Fernandes'},
{ name: 'Ruy Barbosa'},
{ name: 'Santa Cruz'},
{ name: 'Santa Maria'},
{ name: 'Santana do Matos'},
{ name: 'Santana do Seridó'},
{ name: 'Santo Antônio'},
{ name: 'São Bento do Norte'},
{ name: 'São Bento do Trairí'},
{ name: 'São Fernando'},
{ name: 'São Francisco do Oeste'},
{ name: 'São Gonçalo do Amarante'},
{ name: 'São João do Sabugi'},
{ name: 'São José de Mipibu'},
{ name: 'São José do Campestre'},
{ name: 'São José do Seridó'},
{ name: 'São Miguel'},
{ name: 'São Miguel do Gostoso'},
{ name: 'São Paulo do Potengi'},
{ name: 'São Pedro'},
{ name: 'São Rafael'},
{ name: 'São Tomé'},
{ name: 'São Vicente'},
{ name: 'Senador Elói de Souza'},
{ name: 'Senador Georgino Avelino'},
{ name: 'Serra de São Bento'},
{ name: 'Serra do Mel'},
{ name: 'Serra Negra do Norte'},
{ name: 'Serrinha'},
{ name: 'Serrinha dos Pintos'},
{ name: 'Severiano Melo'},
{ name: 'Sítio Novo'},
{ name: 'Taboleiro Grande'},
{ name: 'Taipu'},
{ name: 'Tangará'},
{ name: 'Tenente Ananias'},
{ name: 'Tenente Laurentino Cruz'},
{ name: 'Tibau'},
{ name: 'Tibau do Sul'},
{ name: 'Timbaúba dos Batistas'},
{ name: 'Touros'},
{ name: 'Triunfo Potiguar'},
{ name: 'Umarizal'},
{ name: 'Upanema'},
{ name: 'Várzea'},
{ name: 'Venha-Ver'},
{ name: 'Vera Cruz'},
{ name: 'Viçosa'},
{ name: 'Vila Flor'}
];
