module.exports = [
{ name: 'Alta Floresta d`Oeste'},
{ name: 'Alto Alegre dos Parecis'},
{ name: 'Alto Paraíso'},
{ name: 'Alvorada d`Oeste'},
{ name: 'Ariquemes'},
{ name: 'Buritis'},
{ name: 'Cabixi'},
{ name: 'Cacaulândia'},
{ name: 'Cacoal'},
{ name: 'Campo Novo de Rondônia'},
{ name: 'Candeias do Jamari'},
{ name: 'Castanheiras'},
{ name: 'Cerejeiras'},
{ name: 'Chupinguaia'},
{ name: 'Colorado do Oeste'},
{ name: 'Corumbiara'},
{ name: 'Costa Marques'},
{ name: 'Cujubim'},
{ name: 'Espigão d`Oeste'},
{ name: 'Governador Jorge Teixeira'},
{ name: 'Guajará-Mirim'},
{ name: 'Itapuã do Oeste'},
{ name: 'Jaru'},
{ name: 'Ji-Paraná'},
{ name: 'Machadinho d`Oeste'},
{ name: 'Ministro Andreazza'},
{ name: 'Mirante da Serra'},
{ name: 'Monte Negro'},
{ name: 'Nova Brasilândia d`Oeste'},
{ name: 'Nova Mamoré'},
{ name: 'Nova União'},
{ name: 'Novo Horizonte do Oeste'},
{ name: 'Ouro Preto do Oeste'},
{ name: 'Parecis'},
{ name: 'Pimenta Bueno'},
{ name: 'Pimenteiras do Oeste'},
{ name: 'Porto Velho'},
{ name: 'Presidente Médici'},
{ name: 'Primavera de Rondônia'},
{ name: 'Rio Crespo'},
{ name: 'Rolim de Moura'},
{ name: 'Santa Luzia d`Oeste'},
{ name: 'São Felipe d`Oeste'},
{ name: 'São Francisco do Guaporé'},
{ name: 'São Miguel do Guaporé'},
{ name: 'Seringueiras'},
{ name: 'Teixeirópolis'},
{ name: 'Theobroma'},
{ name: 'Urupá'},
{ name: 'Vale do Anari'},
{ name: 'Vale do Paraíso'},
{ name: 'Vilhena'}
];
