module.exports = [

{ name: 'Abdon Batista'},
{ name: 'Abelardo Luz'},
{ name: 'Agrolândia'},
{ name: 'Agronômica'},
{ name: 'Água Doce'},
{ name: 'Águas de Chapecó'},
{ name: 'Águas Frias'},
{ name: 'Águas Mornas'},
{ name: 'Alfredo Wagner'},
{ name: 'Alto Bela Vista'},
{ name: 'Anchieta'},
{ name: 'Angelina'},
{ name: 'Anita Garibaldi'},
{ name: 'Anitápolis'},
{ name: 'Antônio Carlos'},
{ name: 'Apiúna'},
{ name: 'Arabutã'},
{ name: 'Araquari'},
{ name: 'Araranguá'},
{ name: 'Armazém'},
{ name: 'Arroio Trinta'},
{ name: 'Arvoredo'},
{ name: 'Ascurra'},
{ name: 'Atalanta'},
{ name: 'Aurora'},
{ name: 'Balneário Arroio do Silva'},
{ name: 'Balneário Barra do Sul'},
{ name: 'Balneário Camboriú'},
{ name: 'Balneário Gaivota'},
{ name: 'Bandeirante'},
{ name: 'Barra Bonita'},
{ name: 'Barra Velha'},
{ name: 'Bela Vista do Toldo'},
{ name: 'Belmonte'},
{ name: 'Benedito Novo'},
{ name: 'Biguaçu'},
{ name: 'Blumenau'},
{ name: 'Bocaina do Sul'},
{ name: 'Bom Jardim da Serra'},
{ name: 'Bom Jesus'},
{ name: 'Bom Jesus do Oeste'},
{ name: 'Bom Retiro'},
{ name: 'Bombinhas'},
{ name: 'Botuverá'},
{ name: 'Braço do Norte'},
{ name: 'Braço do Trombudo'},
{ name: 'Brunópolis'},
{ name: 'Brusque'},
{ name: 'Caçador'},
{ name: 'Caibi'},
{ name: 'Calmon'},
{ name: 'Camboriú'},
{ name: 'Campo Alegre'},
{ name: 'Campo Belo do Sul'},
{ name: 'Campo Erê'},
{ name: 'Campos Novos'},
{ name: 'Canelinha'},
{ name: 'Canoinhas'},
{ name: 'Capão Alto'},
{ name: 'Capinzal'},
{ name: 'Capivari de Baixo'},
{ name: 'Catanduvas'},
{ name: 'Caxambu do Sul'},
{ name: 'Celso Ramos'},
{ name: 'Cerro Negro'},
{ name: 'Chapadão do Lageado'},
{ name: 'Chapecó'},
{ name: 'Cocal do Sul'},
{ name: 'Concórdia'},
{ name: 'Cordilheira Alta'},
{ name: 'Coronel Freitas'},
{ name: 'Coronel Martins'},
{ name: 'Correia Pinto'},
{ name: 'Corupá'},
{ name: 'Criciúma'},
{ name: 'Cunha Porã'},
{ name: 'Cunhataí'},
{ name: 'Curitibanos'},
{ name: 'Descanso'},
{ name: 'Dionísio Cerqueira'},
{ name: 'Dona Emma'},
{ name: 'Doutor Pedrinho'},
{ name: 'Entre Rios'},
{ name: 'Ermo'},
{ name: 'Erval Velho'},
{ name: 'Faxinal dos Guedes'},
{ name: 'Flor do Sertão'},
{ name: 'Florianópolis'},
{ name: 'Formosa do Sul'},
{ name: 'Forquilhinha'},
{ name: 'Fraiburgo'},
{ name: 'Frei Rogério'},
{ name: 'Galvão'},
{ name: 'Garopaba'},
{ name: 'Garuva'},
{ name: 'Gaspar'},
{ name: 'Governador Celso Ramos'},
{ name: 'Grão Pará'},
{ name: 'Gravatal'},
{ name: 'Guabiruba'},
{ name: 'Guaraciaba'},
{ name: 'Guaramirim'},
{ name: 'Guarujá do Sul'},
{ name: 'Guatambú'},
{ name: 'Herval d`Oeste'},
{ name: 'Ibiam'},
{ name: 'Ibicaré'},
{ name: 'Ibirama'},
{ name: 'Içara'},
{ name: 'Ilhota'},
{ name: 'Imaruí'},
{ name: 'Imbituba'},
{ name: 'Imbuia'},
{ name: 'Indaial'},
{ name: 'Iomerê'},
{ name: 'Ipira'},
{ name: 'Iporã do Oeste'},
{ name: 'Ipuaçu'},
{ name: 'Ipumirim'},
{ name: 'Iraceminha'},
{ name: 'Irani'},
{ name: 'Irati'},
{ name: 'Irineópolis'},
{ name: 'Itá'},
{ name: 'Itaiópolis'},
{ name: 'Itajaí'},
{ name: 'Itapema'},
{ name: 'Itapiranga'},
{ name: 'Itapoá'},
{ name: 'Ituporanga'},
{ name: 'Jaborá'},
{ name: 'Jacinto Machado'},
{ name: 'Jaguaruna'},
{ name: 'Jaraguá do Sul'},
{ name: 'Jardinópolis'},
{ name: 'Joaçaba'},
{ name: 'Joinville'},
{ name: 'José Boiteux'},
{ name: 'Jupiá'},
{ name: 'Lacerdópolis'},
{ name: 'Lages'},
{ name: 'Laguna'},
{ name: 'Lajeado Grande'},
{ name: 'Laurentino'},
{ name: 'Lauro Muller'},
{ name: 'Lebon Régis'},
{ name: 'Leoberto Leal'},
{ name: 'Lindóia do Sul'},
{ name: 'Lontras'},
{ name: 'Luiz Alves'},
{ name: 'Luzerna'},
{ name: 'Macieira'},
{ name: 'Mafra'},
{ name: 'Major Gercino'},
{ name: 'Major Vieira'},
{ name: 'Maracajá'},
{ name: 'Maravilha'},
{ name: 'Marema'},
{ name: 'Massaranduba'},
{ name: 'Matos Costa'},
{ name: 'Meleiro'},
{ name: 'Mirim Doce'},
{ name: 'Modelo'},
{ name: 'Mondaí'},
{ name: 'Monte Carlo'},
{ name: 'Monte Castelo'},
{ name: 'Morro da Fumaça'},
{ name: 'Morro Grande'},
{ name: 'Navegantes'},
{ name: 'Nova Erechim'},
{ name: 'Nova Itaberaba'},
{ name: 'Nova Trento'},
{ name: 'Nova Veneza'},
{ name: 'Novo Horizonte'},
{ name: 'Orleans'},
{ name: 'Otacílio Costa'},
{ name: 'Ouro'},
{ name: 'Ouro Verde'},
{ name: 'Paial'},
{ name: 'Painel'},
{ name: 'Palhoça'},
{ name: 'Palma Sola'},
{ name: 'Palmeira'},
{ name: 'Palmitos'},
{ name: 'Papanduva'},
{ name: 'Paraíso'},
{ name: 'Passo de Torres'},
{ name: 'Passos Maia'},
{ name: 'Paulo Lopes'},
{ name: 'Pedras Grandes'},
{ name: 'Penha'},
{ name: 'Peritiba'},
{ name: 'Petrolândia'},
{ name: 'Piçarras'},
{ name: 'Pinhalzinho'},
{ name: 'Pinheiro Preto'},
{ name: 'Piratuba'},
{ name: 'Planalto Alegre'},
{ name: 'Pomerode'},
{ name: 'Ponte Alta'},
{ name: 'Ponte Alta do Norte'},
{ name: 'Ponte Serrada'},
{ name: 'Porto Belo'},
{ name: 'Porto União'},
{ name: 'Pouso Redondo'},
{ name: 'Praia Grande'},
{ name: 'Presidente Castelo Branco'},
{ name: 'Presidente Getúlio'},
{ name: 'Presidente Nereu'},
{ name: 'Princesa'},
{ name: 'Quilombo'},
{ name: 'Rancho Queimado'},
{ name: 'Rio das Antas'},
{ name: 'Rio do Campo'},
{ name: 'Rio do Oeste'},
{ name: 'Rio do Sul'},
{ name: 'Rio dos Cedros'},
{ name: 'Rio Fortuna'},
{ name: 'Rio Negrinho'},
{ name: 'Rio Rufino'},
{ name: 'Riqueza'},
{ name: 'Rodeio'},
{ name: 'Romelândia'},
{ name: 'Salete'},
{ name: 'Saltinho'},
{ name: 'Salto Veloso'},
{ name: 'Sangão'},
{ name: 'Santa Cecília'},
{ name: 'Santa Helena'},
{ name: 'Santa Rosa de Lima'},
{ name: 'Santa Rosa do Sul'},
{ name: 'Santa Terezinha'},
{ name: 'Santa Terezinha do Progresso'},
{ name: 'Santiago do Sul'},
{ name: 'Santo Amaro da Imperatriz'},
{ name: 'São Bento do Sul'},
{ name: 'São Bernardino'},
{ name: 'São Bonifácio'},
{ name: 'São Carlos'},
{ name: 'São Cristovão do Sul'},
{ name: 'São Domingos'},
{ name: 'São Francisco do Sul'},
{ name: 'São João Batista'},
{ name: 'São João do Itaperiú'},
{ name: 'São João do Oeste'},
{ name: 'São João do Sul'},
{ name: 'São Joaquim'},
{ name: 'São José'},
{ name: 'São José do Cedro'},
{ name: 'São José do Cerrito'},
{ name: 'São Lourenço do Oeste'},
{ name: 'São Ludgero'},
{ name: 'São Martinho'},
{ name: 'São Miguel da Boa Vista'},
{ name: 'São Miguel do Oeste'},
{ name: 'São Pedro de Alcântara'},
{ name: 'Saudades'},
{ name: 'Schroeder'},
{ name: 'Seara'},
{ name: 'Serra Alta'},
{ name: 'Siderópolis'},
{ name: 'Sombrio'},
{ name: 'Sul Brasil'},
{ name: 'Taió'},
{ name: 'Tangará'},
{ name: 'Tigrinhos'},
{ name: 'Tijucas'},
{ name: 'Timbé do Sul'},
{ name: 'Timbó'},
{ name: 'Timbó Grande'},
{ name: 'Três Barras'},
{ name: 'Treviso'},
{ name: 'Treze de Maio'},
{ name: 'Treze Tílias'},
{ name: 'Trombudo Central'},
{ name: 'Tubarão'},
{ name: 'Tunápolis'},
{ name: 'Turvo'},
{ name: 'União do Oeste'},
{ name: 'Urubici'},
{ name: 'Urupema'},
{ name: 'Urussanga'},
{ name: 'Vargeão'},
{ name: 'Vargem'},
{ name: 'Vargem Bonita'},
{ name: 'Vidal Ramos'},
{ name: 'Videira'},
{ name: 'Vitor Meireles'},
{ name: 'Witmarsum'},
{ name: 'Xanxerê'},
{ name: 'Xavantina'},
{ name: 'Xaxim'},
{ name: 'Zortéa'}
];
