module.exports = [

{ name: 'Amparo de São Francisco' },
{ name: 'Aquidabã' },
{ name: 'Aracaju' },
{ name: 'Arauá' },
{ name: 'Areia Branca' },
{ name: 'Barra dos Coqueiros' },
{ name: 'Boquim' },
{ name: 'Brejo Grande' },
{ name: 'Campo do Brito' },
{ name: 'Canhoba' },
{ name: 'Canindé de São Francisco' },
{ name: 'Capela' },
{ name: 'Carira' },
{ name: 'Carmópolis' },
{ name: 'Cedro de São João' },
{ name: 'Cristinápolis' },
{ name: 'Cumbe' },
{ name: 'Divina Pastora' },
{ name: 'Estância' },
{ name: 'Feira Nova' },
{ name: 'Frei Paulo' },
{ name: 'Gararu' },
{ name: 'General Maynard' },
{ name: 'Gracho Cardoso' },
{ name: 'Ilha das Flores' },
{ name: 'Indiaroba' },
{ name: 'Itabaiana' },
{ name: 'Itabaianinha' },
{ name: 'Itabi' },
{ name: 'Itaporanga d`Ajuda' },
{ name: 'Japaratuba' },
{ name: 'Japoatã' },
{ name: 'Lagarto' },
{ name: 'Laranjeiras' },
{ name: 'Macambira' },
{ name: 'Malhada dos Bois' },
{ name: 'Malhador' },
{ name: 'Maruim' },
{ name: 'Moita Bonita' },
{ name: 'Monte Alegre de Sergipe' },
{ name: 'Muribeca' },
{ name: 'Neópolis' },
{ name: 'Nossa Senhora Aparecida' },
{ name: 'Nossa Senhora da Glória' },
{ name: 'Nossa Senhora das Dores' },
{ name: 'Nossa Senhora de Lourdes' },
{ name: 'Nossa Senhora do Socorro' },
{ name: 'Pacatuba' },
{ name: 'Pedra Mole' },
{ name: 'Pedrinhas' },
{ name: 'Pinhão' },
{ name: 'Pirambu' },
{ name: 'Poço Redondo' },
{ name: 'Poço Verde' },
{ name: 'Porto da Folha' },
{ name: 'Propriá' },
{ name: 'Riachão do Dantas' },
{ name: 'Riachuelo' },
{ name: 'Ribeirópolis' },
{ name: 'Rosário do Catete' },
{ name: 'Salgado' },
{ name: 'Santa Luzia do Itanhy' },
{ name: 'Santa Rosa de Lima' },
{ name: 'Santana do São Francisco' },
{ name: 'Santo Amaro das Brotas' },
{ name: 'São Cristóvão' },
{ name: 'São Domingos' },
{ name: 'São Francisco' },
{ name: 'São Miguel do Aleixo' },
{ name: 'Simão Dias' },
{ name: 'Siriri' },
{ name: 'Telha' },
{ name: 'Tobias Barreto' },
{ name: 'Tomar do Geru' },
{ name: 'Umbaúba' }
];
