module.exports = [

{ name: 'Abreulândia'},
{ name: 'Aguiarnópolis'},
{ name: 'Aliança do Tocantins'},
{ name: 'Almas'},
{ name: 'Alvorada'},
{ name: 'Ananás'},
{ name: 'Angico'},
{ name: 'Aparecida do Rio Negro'},
{ name: 'Aragominas'},
{ name: 'Araguacema'},
{ name: 'Araguaçu'},
{ name: 'Araguaína'},
{ name: 'Araguanã'},
{ name: 'Araguatins'},
{ name: 'Arapoema'},
{ name: 'Arraias'},
{ name: 'Augustinópolis'},
{ name: 'Aurora do Tocantins'},
{ name: 'Axixá do Tocantins'},
{ name: 'Babaçulândia'},
{ name: 'Bandeirantes do Tocantins'},
{ name: 'Barra do Ouro'},
{ name: 'Barrolândia'},
{ name: 'Bernardo Sayão'},
{ name: 'Bom Jesus do Tocantins'},
{ name: 'Brasilândia do Tocantins'},
{ name: 'Brejinho de Nazaré'},
{ name: 'Buriti do Tocantins'},
{ name: 'Cachoeirinha'},
{ name: 'Campos Lindos'},
{ name: 'Cariri do Tocantins'},
{ name: 'Carmolândia'},
{ name: 'Carrasco Bonito'},
{ name: 'Caseara'},
{ name: 'Centenário'},
{ name: 'Chapada da Natividade'},
{ name: 'Chapada de Areia'},
{ name: 'Colinas do Tocantins'},
{ name: 'Colméia'},
{ name: 'Combinado'},
{ name: 'Conceição do Tocantins'},
{ name: 'Couto de Magalhães'},
{ name: 'Cristalândia'},
{ name: 'Crixás do Tocantins'},
{ name: 'Darcinópolis'},
{ name: 'Dianópolis'},
{ name: 'Divinópolis do Tocantins'},
{ name: 'Dois Irmãos do Tocantins'},
{ name: 'Dueré'},
{ name: 'Esperantina'},
{ name: 'Fátima'},
{ name: 'Figueirópolis'},
{ name: 'Filadélfia'},
{ name: 'Formoso do Araguaia'},
{ name: 'Fortaleza do Tabocão'},
{ name: 'Goianorte'},
{ name: 'Goiatins'},
{ name: 'Guaraí'},
{ name: 'Gurupi'},
{ name: 'Ipueiras'},
{ name: 'Itacajá'},
{ name: 'Itaguatins'},
{ name: 'Itapiratins'},
{ name: 'Itaporã do Tocantins'},
{ name: 'Jaú do Tocantins'},
{ name: 'Juarina'},
{ name: 'Lagoa da Confusão'},
{ name: 'Lagoa do Tocantins'},
{ name: 'Lajeado'},
{ name: 'Lavandeira'},
{ name: 'Lizarda'},
{ name: 'Luzinópolis'},
{ name: 'Marianópolis do Tocantins'},
{ name: 'Mateiros'},
{ name: 'Maurilândia do Tocantins'},
{ name: 'Miracema do Tocantins'},
{ name: 'Miranorte'},
{ name: 'Monte do Carmo'},
{ name: 'Monte Santo do Tocantins'},
{ name: 'Muricilândia'},
{ name: 'Natividade'},
{ name: 'Nazaré'},
{ name: 'Nova Olinda'},
{ name: 'Nova Rosalândia'},
{ name: 'Novo Acordo'},
{ name: 'Novo Alegre'},
{ name: 'Novo Jardim'},
{ name: 'Oliveira de Fátima'},
{ name: 'Palmas'},
{ name: 'Palmeirante'},
{ name: 'Palmeiras do Tocantins'},
{ name: 'Palmeirópolis'},
{ name: 'Paraíso do Tocantins'},
{ name: 'Paranã'},
{ name: 'Pau d`Arco'},
{ name: 'Pedro Afonso'},
{ name: 'Peixe'},
{ name: 'Pequizeiro'},
{ name: 'Pindorama do Tocantins'},
{ name: 'Piraquê'},
{ name: 'Pium'},
{ name: 'Ponte Alta do Bom Jesus'},
{ name: 'Ponte Alta do Tocantins'},
{ name: 'Porto Alegre do Tocantins'},
{ name: 'Porto Nacional'},
{ name: 'Praia Norte'},
{ name: 'Presidente Kennedy'},
{ name: 'Pugmil'},
{ name: 'Recursolândia'},
{ name: 'Riachinho'},
{ name: 'Rio da Conceição'},
{ name: 'Rio dos Bois'},
{ name: 'Rio Sono'},
{ name: 'Sampaio'},
{ name: 'Sandolândia'},
{ name: 'Santa Fé do Araguaia'},
{ name: 'Santa Maria do Tocantins'},
{ name: 'Santa Rita do Tocantins'},
{ name: 'Santa Rosa do Tocantins'},
{ name: 'Santa Tereza do Tocantins'},
{ name: 'Santa Terezinha do Tocantins'},
{ name: 'São Bento do Tocantins'},
{ name: 'São Félix do Tocantins'},
{ name: 'São Miguel do Tocantins'},
{ name: 'São Salvador do Tocantins'},
{ name: 'São Sebastião do Tocantins'},
{ name: 'São Valério da Natividade'},
{ name: 'Silvanópolis'},
{ name: 'Sítio Novo do Tocantins'},
{ name: 'Sucupira'},
{ name: 'Taguatinga'},
{ name: 'Taipas do Tocantins'},
{ name: 'Talismã'},
{ name: 'Tocantínia'},
{ name: 'Tocantinópolis'},
{ name: 'Tupirama'},
{ name: 'Tupiratins'},
{ name: 'Wanderlândia'},
{ name: 'Xambioá'}
];

